// chain_seams.gen.h - GENERATED by assets/scripts/gen_chain_seam_tables.py. Do not edit.
#pragma once

#include "door_tables.gen.h"
#include "dungeon_ids.h"

enum {
  kChainSeamKind_Door,
  kChainSeamKind_Stair,
  kChainSeamKind_Hole,
};

enum { kChainSeamDir_None = 0xFF };

typedef struct ChainSeamRow {
  uint8 kind;
  uint8 rando_dungeon;
  uint16 source_room;
  uint16 dest_room;
  uint16 door_id;
  uint8 direction;
  uint8 slot;
} ChainSeamRow;

#define kChainBossSeamCount 9
#define kChainBossOutboundSeamCount 10

extern const ChainSeamRow kChainBossSeams[kChainBossSeamCount];
extern const ChainSeamRow kChainBossOutboundSeams[kChainBossOutboundSeamCount];
