// chains_runtime.h - dungeon-chain runtime hooks.

#ifndef ZELDA3_RANDO_CHAINS_RUNTIME_H_
#define ZELDA3_RANDO_CHAINS_RUNTIME_H_

#include "../types.h"
#include "shuffle_chains.h"

#ifdef __cplusplus
extern "C" {
#endif

// Returns 0xFF for non-pool dungeons. The returned ids are the synthetic
// kEntranceData_* rows generated by gen_chain_boss_entrances.py.
uint8 Chains_BossEntranceForRandoDungeon(uint8 rando_dungeon);

// True only after a loaded asset blob exposes all generated synthetic boss
// entrance rows with the expected room/palace/music metadata.
bool Chains_SyntheticEntrancesAvailable(void);

// Runtime layout state. The seam hooks below are dormant until a layout is
// installed.
bool Chains_RuntimeInstallLayout(const DungeonChainsLayout *layout);
void Chains_RuntimeTeardown(void);
void Chains_RuntimeArmOrigin(uint16 origin_exit_room);
void Chains_RuntimeClearOrigin(void);

typedef struct ChainsRuntimeSession {
  bool origin_active;
  bool terminal_active;
  uint16 origin_exit_room;
  uint8 terminal_dungeon;
} ChainsRuntimeSession;

// Snapshot helpers for the in-flight chain session. The layout must already be
// installed before restore; inactive sessions clear origin/terminal state.
bool Chains_RuntimeGetSession(ChainsRuntimeSession *out);
bool Chains_RuntimeRestoreSession(const ChainsRuntimeSession *session);

// Chain-start door hooks. The entry hook arms the origin session state when an
// installed chain overlay owns `lx`; the exit hook consumes it only when the
// resolved dungeon-exit room is one of the chain pool's main doors.
bool Chains_RuntimeRecordDoorEntry(uint16 lx);
// Clears carried tagalong/follower state before a chain-start entrance load so a
// follower cannot ride an overworld dungeon door into a foreign chain element.
void Chains_ClearFollowerForChainStart(void);
uint16 Chains_RuntimeConsumeMainExitOrigin(uint16 resolved_exit_room);
void Chains_RuntimeSelfCheck(void);

// Generic inbound boss-seam hook. `kind` is kChainSeamKind_* and `slot` is the
// generated seam slot, or 0xFF when the caller has no slot identity.
bool Chains_TryBossSeamHop(uint8 kind,
                           uint8 direction,
                           uint16 source_room,
                           uint16 vanilla_destination_room,
                           uint8 slot);

bool Chains_TryTerminalOutboundSeam(uint8 kind,
                                    uint8 direction,
                                    uint16 source_room,
                                    uint16 vanilla_destination_room,
                                    uint8 slot);

// One-shot escape for entering an already-cleared terminal boss room whose
// post-kill shutters would otherwise seal Link inside before any transition can
// reach Chains_TryTerminalOutboundSeam.
bool Chains_TryClearedTerminalReentryExit(void);

// Consumed at the top of Dungeon_LoadEntrance. True means this entrance load is
// chain-owned and must not recache the overworld *_exit state.
bool Chains_ConsumeHopPending(void);

// Synthetic boss entrances are kEntranceData rows, not real inter-room
// transitions, so fix up door-based arrivals after Dungeon_LoadEntrance has read
// the asset row. Returns true only when it adjusted the active entrance.
bool Chains_TryApplyBossEntranceLanding(void);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // ZELDA3_RANDO_CHAINS_RUNTIME_H_
