// chain_seams.gen.c - GENERATED by assets/scripts/gen_chain_seam_tables.py. Do not edit.
#include "chain_seams.gen.h"

const ChainSeamRow kChainBossSeams[kChainBossSeamCount] = {
  {kChainSeamKind_Door, kRandoDungeon_EasternPalace, 0x0D8, 0x0C8, 87, kDoorTblDir_North, 2}, // Eastern Duo Eyegores NE -> Eastern Palace
  {kChainSeamKind_Door, kRandoDungeon_DesertPalace, 0x043, 0x033, 53, kDoorTblDir_North, 0}, // Desert Wall Slide NW -> Desert Palace
  {kChainSeamKind_Stair, kRandoDungeon_TowerOfHera, 0x017, 0x007, 321, kDoorTblDir_Up, 1}, // Hera 5F Up Stairs -> Tower of Hera
  {kChainSeamKind_Door, kRandoDungeon_PalaceOfDarkness, 0x06A, 0x05A, 710, kDoorTblDir_North, 2}, // PoD Dark Alley NE -> Palace of Darkness
  {kChainSeamKind_Door, kRandoDungeon_SwampPalace, 0x016, 0x006, 932, kDoorTblDir_North, 0}, // Swamp T NW -> Swamp Palace
  {kChainSeamKind_Door, kRandoDungeon_ThievesTown, 0x0BC, 0x0AC, 1131, kDoorTblDir_North, 2}, // Thieves Hallway NE -> Thieves Town
  {kChainSeamKind_Hole, kRandoDungeon_IcePalace, 0x0CE, 0x0DE, 424, kChainSeamDir_None, 0}, // Ice Antechamber Hole -> Ice Palace
  {kChainSeamKind_Door, kRandoDungeon_MiseryMire, 0x0A0, 0x090, 529, kDoorTblDir_North, 0}, // Mire Antechamber NW -> Misery Mire
  {kChainSeamKind_Door, kRandoDungeon_TurtleRock, 0x0B4, 0x0A4, 1032, kDoorTblDir_North, 0}, // TR Final Abyss NW -> Turtle Rock
};

const ChainSeamRow kChainBossOutboundSeams[kChainBossOutboundSeamCount] = {
  {kChainSeamKind_Door, kRandoDungeon_EasternPalace, 0x0C8, 0x0D8, 64, kDoorTblDir_South, 2}, // Eastern Boss SE -> room 0x0D8
  {kChainSeamKind_Door, kRandoDungeon_DesertPalace, 0x033, 0x043, 9, kDoorTblDir_South, 0}, // Desert Boss SW -> room 0x043
  {kChainSeamKind_Hole, kRandoDungeon_TowerOfHera, 0x007, 0x017, 336, kChainSeamDir_None, 0}, // Hera Boss Inner Hole -> room 0x017
  {kChainSeamKind_Hole, kRandoDungeon_TowerOfHera, 0x007, 0x017, 337, kChainSeamDir_None, 0}, // Hera Boss Outer Hole -> room 0x017
  {kChainSeamKind_Stair, kRandoDungeon_TowerOfHera, 0x007, 0x017, 335, kDoorTblDir_Down, 1}, // Hera Boss Down Stairs -> room 0x017
  {kChainSeamKind_Door, kRandoDungeon_PalaceOfDarkness, 0x05A, 0x06A, 692, kDoorTblDir_South, 2}, // PoD Boss SE -> room 0x06A
  {kChainSeamKind_Door, kRandoDungeon_SwampPalace, 0x006, 0x016, 872, kDoorTblDir_South, 0}, // Swamp Boss SW -> room 0x016
  {kChainSeamKind_Door, kRandoDungeon_ThievesTown, 0x0AC, 0x0BC, 1112, kDoorTblDir_South, 2}, // Thieves Boss SE -> room 0x0BC
  {kChainSeamKind_Door, kRandoDungeon_MiseryMire, 0x090, 0x0A0, 540, kDoorTblDir_South, 0}, // Mire Boss SW -> room 0x0A0
  {kChainSeamKind_Door, kRandoDungeon_TurtleRock, 0x0A4, 0x0B4, 976, kDoorTblDir_South, 0}, // TR Boss SW -> room 0x0B4
};
