// door_tables.gen.h — GENERATED by assets/scripts/gen_door_tables.py. Do not edit.
#pragma once
#include "../types.h"

enum {  // DoorTbl door types
  kDoorTblType_Normal, kDoorTblType_SpiralStairs, kDoorTblType_StraightStairs,
  kDoorTblType_Ladder, kDoorTblType_Open, kDoorTblType_Hole, kDoorTblType_Warp,
  kDoorTblType_Interior, kDoorTblType_Logical,
};
enum {  // DoorTbl directions
  kDoorTblDir_North, kDoorTblDir_South, kDoorTblDir_West, kDoorTblDir_East,
  kDoorTblDir_Up, kDoorTblDir_Down,
};
enum {  // DoorTblDoor flags
  kDoorTblFlag_Toggle = 0x1, kDoorTblFlag_Blocked = 0x2,
  kDoorTblFlag_Trapped = 0x4, kDoorTblFlag_Stonewall = 0x8,
  kDoorTblFlag_VanillaSmallKey = 0x10, kDoorTblFlag_VanillaBigKey = 0x20,
  kDoorTblFlag_Ugly = 0x40, kDoorTblFlag_DeadEnd = 0x80,
  kDoorTblFlag_Portal = 0x100, kDoorTblFlag_InPool = 0x200,
  kDoorTblFlag_CrystalBlue = 0x400, kDoorTblFlag_CrystalOrange = 0x800,
  kDoorTblFlag_VanillaTeleport = 0x1000,
};
enum {  // DoorTblEvent ids
  kDoorEvent_Trench1Filled = 0,
  kDoorEvent_Trench2Filled = 1,
  kDoorEvent_DrainedSwamp = 2,
  kDoorEvent_OpenFloodgate = 3,
  kDoorEvent_HiddenPits = 4,
  kDoorEvent_ConvenientBlock = 5,
  kDoorEvent_ShiningLight = 6,
  kDoorEvent_MaidenRescued = 7,
  kDoorEvent_MaidenUnmasked = 8,
  kDoorEvent_AtticCrackedFloor = 9,
};
enum {  // door-rule bytecode ops (kDoorTblRuleBlob)
  kDoorRuleOp_True, kDoorRuleOp_False, kDoorRuleOp_And, kDoorRuleOp_Or,
  kDoorRuleOp_Not, kDoorRuleOp_Vm, kDoorRuleOp_Event, kDoorRuleOp_CReach,
  kDoorRuleOp_Reach,
};

typedef struct DoorTblDoor {
  uint16 name_off;
  uint16 region;          // kDoorTblRegions index
  uint16 vanilla_partner;  // door id, 0xFFFF none
  uint16 flags;
  uint8 room;
  uint8 type;
  uint8 direction;
  uint8 door_index;        // 0..2 within the edge
  uint8 layer;
  uint8 pos;               // doorListPos, 0xFF none
  uint8 pos_byte;          // RoomData Position code (door-list low byte)
  uint8 kind;              // RoomData DoorKind code (door-list high byte)
  uint8 trap_flag;
  uint8 quadrant;
  int8 shift_x;
  int8 shift_y;
  uint8 dungeon;
} DoorTblDoor;

typedef struct DoorTblRegion {
  uint16 name_off;
  uint8 dungeon;
  uint8 flags;  // 1 = crystal switch present
} DoorTblRegion;

typedef struct DoorTblEdge {
  uint16 from_region;
  uint16 to_region;
  uint16 rule;   // offset into kDoorTblRuleBlob, 0xFFFF = always
  uint16 door;   // door id this edge crosses, 0xFFFF = logical
  uint8 is_pool; // 1 = vanilla connection of a shuffleable stub
} DoorTblEdge;

typedef struct DoorTblPair {
  uint16 a, b;
  uint8 one_way;
} DoorTblPair;

typedef struct DoorTblLocation {
  uint16 fork_loc_id;
  uint16 region;
  uint16 rule;
} DoorTblLocation;

typedef struct DoorTblEvent {
  uint8 event_id;
  uint16 region;
  uint16 rule;
} DoorTblEvent;

typedef struct DoorTblDropKey {
  uint8 dungeon;
  uint16 region;
  uint16 rule;
} DoorTblDropKey;

typedef struct DoorTblDungeon {
  uint16 name_off;
  uint8 chest_small_keys;
  uint8 has_big_key;
  uint16 region_first;
  uint16 region_count;
  uint16 small_key_item;
  uint16 big_key_item;
} DoorTblDungeon;

typedef struct DoorTblPath {
  uint8 dungeon;
  uint8 kind;  // 0 = boss/required, 1 = drop-exit
  uint16 region;
} DoorTblPath;

typedef struct DoorTblRoomDoor {
  uint8 pos_byte;
  uint8 kind;
} DoorTblRoomDoor;
typedef struct DoorTblRoom {
  uint8 room;
  uint8 count;
  uint16 first;  // into kDoorTblRoomDoors
} DoorTblRoom;

typedef struct DoorTblPairedKind {
  uint16 a, b;
  uint8 pair;
} DoorTblPairedKind;

#define kDoorTbl_DoorCount 1200
#define kDoorTbl_RegionCount 577
#define kDoorTbl_EdgeCount 1061
#define kDoorTbl_PairCount 149
#define kDoorTbl_LocationCount 134
#define kDoorTbl_EventCount 10
#define kDoorTbl_DropKeyCount 32
#define kDoorTbl_DungeonCount 13
#define kDoorTbl_PathCount 16
#define kDoorTbl_RoomCount 186
#define kDoorTbl_PairedKindCount 38
#define kDoorTbl_VmPredCount 69
#define kDoorTbl_RuleBlobSize 750

extern const char kDoorTblNames[];
extern const DoorTblDoor kDoorTblDoors[kDoorTbl_DoorCount];
extern const DoorTblRegion kDoorTblRegions[kDoorTbl_RegionCount];
extern const DoorTblEdge kDoorTblEdges[kDoorTbl_EdgeCount];
extern const DoorTblPair kDoorTblVanillaPairs[kDoorTbl_PairCount];
extern const DoorTblLocation kDoorTblLocations[kDoorTbl_LocationCount];
extern const DoorTblEvent kDoorTblEvents[kDoorTbl_EventCount];
extern const DoorTblDropKey kDoorTblDropKeys[kDoorTbl_DropKeyCount];
extern const DoorTblDungeon kDoorTblDungeons[kDoorTbl_DungeonCount];
extern const DoorTblPath kDoorTblPaths[kDoorTbl_PathCount];
extern const DoorTblRoom kDoorTblRooms[kDoorTbl_RoomCount];
extern const DoorTblRoomDoor kDoorTblRoomDoors[];
extern const DoorTblPairedKind kDoorTblPairedKinds[kDoorTbl_PairedKindCount];
extern const uint8 kDoorTblRuleBlob[kDoorTbl_RuleBlobSize];
