// Inverted overworld per-screen tile-overlay data + applier.
//
// ALTTPR realizes the Light/Dark-world topology inversion (Inverted mode) via a
// per-screen RLE tile-overlay subsystem: z3randomizer's Overworld_LoadNewTiles
// looks up OverworldMapChangePointers[screen] and applies a stream of tile-write
// / stripe / RLE commands over the freshly-decompressed map16 buffer ($7E2000 =
// dung_bg2 / g_ram[0x2000]) before it is converted to map8 for display.
//
// This fork reimplements that engine in C (Overworld_ApplyInvertedTiles, in
// overworld.c) and consumes the SAME wire format. The data is a single fixed
// topology (it does not vary by seed), so it is a checked-in static C table
// (inverted_maps.c, generated by assets/scripts/gen_inverted_maps.py from
// invertedmaps.asm) — NOT a zelda3_assets.dat blob and NOT rando codegen.
//
// The fork only ever applies this when ALREADY in the Inverted world-state
// (Rando_GetActiveWorldState() == kWorldState_Inverted under
// kFeatures1_RandomizerActive); the generator therefore resolves the asm's
// InvertedMode-conditional commands at conversion time (InvertedOnly -> no-op,
// SkipIfInverted -> unconditional jump). The two CustomCommand vectors carry
// real per-screen logic and are re-encoded as OWW_CMD_CUSTOM + a custom-id the
// applier dispatches (pyramid-of-power hole after Agahnim; progress-gated 5B
// warp tile).
#ifndef RANDO_INVERTED_MAPS_H_
#define RANDO_INVERTED_MAPS_H_

#include "../types.h"

// Stream sentinels (mirror invertedmaps.asm). 0xFFFF is OWW_END at the top level
// and OWW_SKIP (skip-this-position) inside a stripe tile-list — context decides.
#define OWW_END               0xFFFF
#define OWW_SKIP              0xFFFF

// Fork-private command opcode re-encoding the asm's !OWW_CustomCommand vectors.
#define OWW_CMD_CUSTOM        0x8011
#define OWW_CUSTOM_MAP1B_AGA  0  // pyramid-of-power hole, gated on Agahnim defeat
#define OWW_CUSTOM_MAP5B_WARP 1  // screen 0x5B warp tile, gated on progress

// Generated data (inverted_maps.c).
extern const uint16 kInvertedMapData[];
extern const unsigned kInvertedMapDataLen;
extern const uint16 kInvertedMapOffsets[128];  // 0xFFFF = no overlay for screen

// Apply the inverted tile overlay for the current overworld screen onto the
// live map16 buffer (dung_bg2 / g_ram[0x2000]). No-op for screens with no
// overlay or for screen indices >= 0x80. Caller must already have gated on the
// Inverted world-state.
void Overworld_ApplyInvertedTiles(void);

#endif  // RANDO_INVERTED_MAPS_H_
