// npc_soul_tables.h — GENERATED by assets/scripts/gen_npc_soul_tables.py
// (add-npc-souls). Curated roster + asset-derived site rows; do not
// hand-edit — regenerate (script asserts ids, sites, and exclusions).
#pragma once
#include "../types.h"

enum {
  kNpcSoul_Sahasrahla = 0,
  kNpcSoul_KingZora = 1,
  kNpcSoul_Witch = 2,
  kNpcSoul_MagicBat = 3,
  kNpcSoul_SickKid = 4,
  kNpcSoul_BottleMerchant = 5,
  kNpcSoul_Hobo = 6,
  kNpcSoul_OldMan = 7,
  kNpcSoul_Stumpy = 8,
  kNpcSoul_Catfish = 9,
  kNpcSoul_WaterfallFairy = 10,
  kNpcSoul_PyramidFairy = 11,
  kNpcSoul_HomeSmith = 12,
  kNpcSoul_FrogSmith = 13,
  kNpcSoul_MiddleAgedMan = 14,
  kNpcSoul_DiggingGame = 15,
  kNpcSoul_ChestGame = 16,
  kNpcSoul_MazeGameLady = 17,
  kNpcSoul_MazeGameGuy = 18,
  kNpcSoul_MMCNpc = 19,
  kNpcSoul_HypeCaveNpc = 20,
  kNpcSoul_Kiki = 21,
  kNpcSoul_BombShopDealer = 22,
  kNpcSoul_Uncle = 23,
  kNpcSoulCount = 24,
};

// Suppression site: sprite `type` at `key` (room id when `is_room`,
// else overworld area id), `world`: 0=any 1=LW-only 2=DW-only.
// Sorted by (type, key) — linear scan is fine (22 rows, spawn-time).
// INVARIANT: consulted ONLY by the static-room and overworld-proxima
// hooks — NEVER by Sprite_SpawnDynamicallyEx. The dynamic 0xC0 reward
// deliveries (King Zora flippers / Catfish medallion) must always
// spawn; only the catfish's own STATIC area entry is suppressed.
typedef struct NpcSoulSite {
  uint8 type;
  uint8 is_room;
  uint16 key;
  uint8 world;
  uint8 npc_soul;  // kNpcSoul_*
} NpcSoulSite;

// Exactly one TU (souls.c) defines NPC_SOUL_TABLES_IMPL (the
// SOUL_TABLES_IMPL pattern).
enum { kNpcSoulSiteCount = 23 };
extern const NpcSoulSite kNpcSoulSites[kNpcSoulSiteCount];
extern const char *const kNpcSoulNames[kNpcSoulCount];

#ifdef NPC_SOUL_TABLES_IMPL
const NpcSoulSite kNpcSoulSites[kNpcSoulSiteCount] = {
  { 0x16, 1, 0x0105, 0, kNpcSoul_Sahasrahla },
  { 0x1A, 0, 0x0069, 2, kNpcSoul_FrogSmith },
  { 0x1A, 1, 0x0121, 0, kNpcSoul_HomeSmith },
  { 0x1F, 1, 0x0102, 0, kNpcSoul_SickKid },
  { 0x2B, 0, 0x0080, 0, kNpcSoul_Hobo },
  { 0x2E, 0, 0x006A, 2, kNpcSoul_Stumpy },
  { 0x2F, 0, 0x0028, 1, kNpcSoul_MazeGameLady },
  { 0x30, 0, 0x0028, 1, kNpcSoul_MazeGameGuy },
  { 0x36, 0, 0x0016, 1, kNpcSoul_Witch },
  { 0x39, 0, 0x003A, 1, kNpcSoul_MiddleAgedMan },
  { 0x3A, 1, 0x00E3, 0, kNpcSoul_MagicBat },
  { 0x52, 0, 0x0081, 0, kNpcSoul_KingZora },
  { 0x73, 1, 0x0055, 0, kNpcSoul_Uncle },
  { 0x75, 0, 0x0018, 1, kNpcSoul_BottleMerchant },
  { 0xAD, 1, 0x00E4, 0, kNpcSoul_OldMan },
  { 0xAD, 1, 0x00F0, 0, kNpcSoul_OldMan },
  { 0xB5, 1, 0x011C, 0, kNpcSoul_BombShopDealer },
  { 0xB6, 0, 0x005E, 2, kNpcSoul_Kiki },
  { 0xBB, 1, 0x0106, 0, kNpcSoul_ChestGame },
  { 0xBB, 1, 0x011E, 0, kNpcSoul_HypeCaveNpc },
  { 0xBB, 1, 0x0123, 0, kNpcSoul_MMCNpc },
  { 0xC0, 0, 0x004F, 2, kNpcSoul_Catfish },
  { 0xD5, 0, 0x0068, 2, kNpcSoul_DiggingGame },
};
const char *const kNpcSoulNames[kNpcSoulCount] = {
  "Soul_Npc_Sahasrahla",
  "Soul_Npc_KingZora",
  "Soul_Npc_Witch",
  "Soul_Npc_MagicBat",
  "Soul_Npc_SickKid",
  "Soul_Npc_BottleMerchant",
  "Soul_Npc_Hobo",
  "Soul_Npc_OldMan",
  "Soul_Npc_Stumpy",
  "Soul_Npc_Catfish",
  "Soul_Npc_WaterfallFairy",
  "Soul_Npc_PyramidFairy",
  "Soul_Npc_HomeSmith",
  "Soul_Npc_FrogSmith",
  "Soul_Npc_MiddleAgedMan",
  "Soul_Npc_DiggingGame",
  "Soul_Npc_ChestGame",
  "Soul_Npc_MazeGameLady",
  "Soul_Npc_MazeGameGuy",
  "Soul_Npc_MMCNpc",
  "Soul_Npc_HypeCaveNpc",
  "Soul_Npc_Kiki",
  "Soul_Npc_BombShopDealer",
  "Soul_Npc_Uncle",
};
#endif  // NPC_SOUL_TABLES_IMPL

// Souls with no sprite site (gated at their grant branch / trigger):
//   kNpcSoul_WaterfallFairy
//   kNpcSoul_PyramidFairy

