// rando_hints.h — deterministic Hints v2 plan, delivery, and discovery APIs.
//
// A seed owns one immutable, versioned semantic plan. The plan contains up to
// 24 unique facts: 15 telepathic-tile primaries, one head fact for each of the
// three paid queues, and up to two exact reserve facts per paid queue.
// Discovery is mutable session state and is deliberately kept separate from
// the immutable fact/source plan and from the canonical race spoiler stamp.

#ifndef ZELDA3_RANDO_HINTS_H_
#define ZELDA3_RANDO_HINTS_H_

#include "../types.h"
#include "rando_placement.h"

// ---------------------------------------------------------------------------
// Hint-NPC id space.
//
// IDs 1-15: 15 telepathic tiles (ALTTPR `HintService.php:59-75`).
// ID 16   : Murahdahla static per-goal text (ALTTPR `Randomizer.php:1029`).
// IDs 17-20: zelda3-fork extensions (NOT in ALTTPR upstream). Improve
//           accessibility by routing existing in-game NPC dialogue
//           through the hint generator.
//
// Order is stable for spoiler-JSON keys; fork extensions use a
// `fork_` prefix on their string IDs so ALTTPR-diff-ability is
// preserved for the core 16 entries.
// ---------------------------------------------------------------------------
typedef enum RandoHintNpc {
  kRandoHintNpc_None = 0,

  // 15 telepathic tiles (ALTTPR `HintService.php:59-75`).
  kRandoHintNpc_TeleEasternPalace          = 1,
  kRandoHintNpc_TeleTowerOfHera_Floor4     = 2,
  kRandoHintNpc_TeleSpectacleRock          = 3,
  kRandoHintNpc_TeleSwampEntrance          = 4,
  kRandoHintNpc_TeleThievesTownUpstairs    = 5,
  kRandoHintNpc_TeleMiseryMire             = 6,
  kRandoHintNpc_TelePalaceOfDarkness       = 7,
  kRandoHintNpc_TeleDesertBonkTorchRoom    = 8,
  kRandoHintNpc_TeleCastleTower            = 9,
  kRandoHintNpc_TeleIceLargeRoom           = 10,
  kRandoHintNpc_TeleTurtleRock             = 11,
  kRandoHintNpc_TeleIceEntrace             = 12,  // [sic] ALTTPR typo preserved
  kRandoHintNpc_TeleIceStalfosKnightsRoom  = 13,
  kRandoHintNpc_TeleTowerOfHera_Entrance   = 14,
  kRandoHintNpc_TeleSouthEastDarkworldCave = 15,

  // Murahdahla — static per-goal text for Triforce Hunt and Ganon Hunt.
  // Not generated by HintService; lives at `Randomizer.php:1029`.
  kRandoHintNpc_Murahdahla                 = 16,

  // Fork extensions (NOT in ALTTPR). The Storyteller is the 20-rupee
  // health-restoring NPC `Sprite_28_DarkWorldHintNPC` — vanilla framing
  // ("I'll give you a tip for
  // 20 rupees") makes it a natural fit. The 3 Fortune Tellers are
  // currently near-useless cosmetic NPCs whose framing ("I see your
  // future") matches hint-distribution.
  kRandoHintNpc_ForkStoryteller            = 17,
  kRandoHintNpc_ForkFortuneTellerKak       = 18,
  kRandoHintNpc_ForkFortuneTellerDark      = 19,
  kRandoHintNpc_ForkFortuneTellerLakeHylia = 20,

  kRandoHintNpc__Count                     = 21,
} RandoHintNpc;

// ---------------------------------------------------------------------------
// Settings axis: public Off/Balanced mode (binary on disk, matching ALTTPR
// `spoil.Hints` at `HintService.php:54` which tests `=== 'on'`).
//
// The stable enum value occupies canonical byte 22 (joined the settings hash
// at kGeneratorVersion 14); see Settings_CanonicalSerialize/Deserialize in
// rando_settings.c.
// ---------------------------------------------------------------------------
typedef enum RandoHintsMode {
  kHintsMode_Off = 0,
  // Serialized value 1 historically appeared as on/full/sahasrahla. Hints v2
  // normalizes every such public alias to the one supported Balanced mode.
  kHintsMode_Balanced = 1,
  kHintsMode_On = kHintsMode_Balanced,
} RandoHintsMode;

// ---------------------------------------------------------------------------
// Immutable plan and mutable discovery state.
//
// New saves persist the algorithm/text-schema versions and the SHA-256 digest
// of the complete ordered plan. A loader must select that exact algorithm and
// verify the digest; missing, unsupported, or mismatched metadata fails hints
// closed with neutral owned-surface text. Full deck bytes are reconstructed,
// never serialized.
// ---------------------------------------------------------------------------
#define kRandoHintPlanLegacyAlgorithmVersion 1u
#define kRandoHintLegacyTextSchemaVersion    1u
#define kRandoHintPlanAlgorithmVersion       2u
#define kRandoHintTextSchemaVersion          2u
// Generator 156 minted the frozen 1/1 spoiler schema; generator 157 was the
// first schema-bearing feature-line version with configurable policy plus the
// additive 2/2 spoiler fields. The 157 constant is therefore a historical
// schema floor, not the current generator version. Race reveal retains an
// explicit frozen-156 compatibility path while every other non-current
// generator remains unsupported.
#define kRandoHintLegacyGeneratorVersion     156u
#define kRandoHintConfigurableGeneratorVersion 157u
#define kRandoHintPlanDigestBytes      32u
#define kRandoHintPlanMaxFacts         24u
#define kRandoHintPlanPrimaryTarget    18u
#define kRandoHintPaidSourceCount      3u
#define kRandoHintPaidQueueCapacity    3u
#define kRandoHintDiscoveryBytes       4u
#define kRandoHintNoFact               0xFFu

typedef enum RandoHintFactKind {
  kRandoHintFact_PriorityItem = 1,
  kRandoHintFact_MajorItem,
  kRandoHintFact_HighFrictionLocation,
  kRandoHintFact_Goal,
  kRandoHintFact_ActiveSetting,
  kRandoHintFact_RegionValue,
  kRandoHintFact_Useful,
  kRandoHintFact_Flavor,
} RandoHintFactKind;

typedef enum RandoHintTemplateId {
  kRandoHintTemplate_ExactPlacement = 1,
  kRandoHintTemplate_Goal,
  kRandoHintTemplate_ActiveSetting,
  kRandoHintTemplate_RegionValue,
  kRandoHintTemplate_Flavor,
} RandoHintTemplateId;

typedef enum RandoHintPlanStatus {
  kRandoHintPlanStatus_None = 0,
  kRandoHintPlanStatus_Ready,
  kRandoHintPlanStatus_Off,
  kRandoHintPlanStatus_MissingMetadata,
  kRandoHintPlanStatus_UnsupportedAlgorithm,
  kRandoHintPlanStatus_UnsupportedTextSchema,
  kRandoHintPlanStatus_DigestMismatch,
  kRandoHintPlanStatus_BuildFailed,
} RandoHintPlanStatus;

typedef enum RandoHintPaidSource {
  kRandoHintPaidSource_Storyteller = 0,
  kRandoHintPaidSource_FortuneLight = 1,
  kRandoHintPaidSource_FortuneDark = 2,
} RandoHintPaidSource;

typedef struct RandoHintFact {
  uint8 fact_id;
  uint8 kind;
  uint8 template_id;
  uint8 primary;
  uint16 location_id;  // 0xFFFF for non-placement facts.
  uint16 item_id;      // 0xFFFF for non-placement facts.
  uint16 region_id;    // 0xFFFF when not region-scoped.
  // Stable template-specific semantic payload: Goal enum, active-setting
  // subject id, literal region-value count, or flavor id. Zero for exact
  // placement facts. Rendered/localized strings are not part of plan identity.
  uint16 template_parameter;
  char text[160];      // complete human-readable journal/spoiler text.
  char game_text[96];  // complete, verified three-row in-game rendering.
} RandoHintFact;

typedef struct RandoHintPlan {
  uint16 algorithm_version;
  uint16 text_schema_version;
  uint8 mode;
  // Normalized seed policy. Enabled legacy 1/1 plans carry the compatibility
  // defaults (15 tiles, Variety, three clues per paid service); legacy Off is
  // empty. Algorithm 2 binds these values into its semantic digest before
  // facts/assignments.
  uint8 tile_target;
  uint8 mix;
  uint8 paid_depth;
  uint8 fact_count;
  uint8 primary_fact_by_npc[kRandoHintNpc__Count];
  uint8 paid_queue[kRandoHintPaidSourceCount][kRandoHintPaidQueueCapacity];
  uint8 paid_count[kRandoHintPaidSourceCount];
  uint8 murahdahla_active;
  uint8 digest[kRandoHintPlanDigestBytes];
  char murahdahla_text[160];
  RandoHintFact facts[kRandoHintPlanMaxFacts];
} RandoHintPlan;

typedef struct RandoHintPersistedState {
  uint16 algorithm_version;  // 0 means metadata absent.
  uint16 text_schema_version;
  uint8 plan_digest[kRandoHintPlanDigestBytes];
  uint8 discovered[kRandoHintDiscoveryBytes];
} RandoHintPersistedState;

// ---------------------------------------------------------------------------
// Dialogue-ID labels.
//
// `kRandoHintDialogueBase + (RandoHintNpc - 1)` gives each hint NPC a stable
// 16-bit spoiler label, positionally mapped. It is NOT a runtime dialogue
// carve. The in-game intercept does not key off this range:
// `Text_LoadCharacterBuffer` calls `Rando_RenderHintMessage`, which replaces
// the vanilla tile text in place when the requested `dialogue_message_index`
// is one of the 15 vanilla telepathic-tile message IDs (`kHintTileMsgIds`,
// 0xB4,0xB5,0xB8..0xBB,0xBE..0xC6 — 0xB4 IS the Eastern Palace tile and is
// included; 0xC7 = Chris Houlihan room and is excluded; see the array's comment
// in rando_hints.c). `Rando_RemapTeleMsg` is a compatibility no-op and is not
// used by the runtime intercept.
// ---------------------------------------------------------------------------
#define kRandoHintDialogueBase  0x200u
#define kRandoHintDialogueCount 20u  // = kRandoHintNpc__Count - 1
#define kRandoHintDialogueEnd   (kRandoHintDialogueBase + kRandoHintDialogueCount)

// Legacy compatibility no-op retained for out-of-tree callers. Runtime
// interception replaces the 15 verified vanilla message IDs in
// Rando_RenderHintMessage and does not carve a synthetic dialogue range.
uint16 Rando_RemapTeleMsg(uint16 vanilla_id, uint16 room_or_area, bool is_overworld);

// Read-only, main-thread caller-owned builder used by generation, spoilers,
// race reveal, and the active-slot installer. It never mutates the live
// plan/discovery/paid state, but it consumes the currently installed effective
// entrance-region overlay; callers must build before clearing that overlay.
// Requested settings are canonicalized internally to the exact effective
// settings image persisted and recovered at activation.
// `spheres` is reserved for compatible future algorithm versions; the current
// algorithm intentionally derives no plan identity from mutable sphere output.
bool Rando_BuildHintPlan(const RandoSettings *settings,
                         const RandoPlacementTable *placements,
                         const RandoSpheres *spheres,
                         uint16 algorithm_version,
                         uint16 text_schema_version,
                         RandoHintPlan *out);

// Compatibility helper: build and install a fresh current plan with discovery
// cleared. Active gameplay reconstruction uses Rando_RebuildHints instead.
bool Rando_GenerateHints(const RandoSettings *settings,
                         const RandoPlacementTable *placements,
                         const RandoSpheres *spheres);

// Reconstruct an ACTIVE slot plan from the current persisted 2/2 state most
// recently supplied to Rando_HintsImportPersistedState. Missing, legacy,
// unsupported, or mismatched metadata returns true after installing a
// fail-closed neutral plan status; it never guesses a different plan. A
// structural build failure returns false. The frozen 1/1 builder is direct
// race-reveal compatibility, not a sidecar/snapshot format.
bool Rando_RebuildHints(const RandoSettings *settings,
                        const RandoPlacementTable *placements,
                        const RandoSpheres *spheres);

// Install the persisted identity/discovery expectation used by the next
// Rando_RebuildHints call. NULL means metadata is missing (fail closed).
void Rando_HintsImportPersistedState(const RandoHintPersistedState *state);

// Export the current live 2/2 plan identity + discovery. Returns true for a
// verified Ready plan or the certified empty Off plan; legacy,
// unavailable/mismatched state is never persisted as a newly blessed identity.
bool Rando_HintsExportPersistedState(RandoHintPersistedState *out);
bool Rando_HintPlanExportPersistedState(const RandoHintPlan *plan,
                                        RandoHintPersistedState *out);

RandoHintPlanStatus Rando_GetHintPlanStatus(void);
const char *Rando_GetHintPlanStatusName(void);

// Source-driven, player-facing item names shared by hint text and other
// disclosure surfaces. `compact` selects the lossless compact-qualified form
// generated from hint_metadata.yaml. Returns NULL for an unknown item id.
const char *Rando_GetHintItemDisplayName(uint16 item_id, bool compact);
uint8 Rando_GetHintFactCount(void);
const RandoHintFact *Rando_GetHintFact(uint8 fact_id);
// Resolve a delivery fact to its immutable source assignment. Tile facts
// return their tile NPC and queue_index 0. Paid facts return Storyteller,
// Fortune Light (Kakariko/Lake shared), or Fortune Dark plus queue index 0..2.
// Returns false for invalid or unassigned facts without modifying state.
bool Rando_GetHintFactAssignment(uint8 fact_id, RandoHintNpc *out_npc,
                                 uint8 *out_queue_index);
bool Rando_IsHintFactDiscovered(uint8 fact_id);
bool Rando_IsHintFactResolved(uint8 fact_id);
uint8 Rando_GetHintDiscoveredCount(void);
// Returns the 32-byte digest for Ready or the certified empty Off plan.
// Returns NULL for every unavailable/fail-closed status.
const uint8 *Rando_GetHintPlanDigest(void);
uint16 Rando_GetHintPlanAlgorithmVersion(void);
uint16 Rando_GetHintTextSchemaVersion(void);

// Paid delivery transaction hooks. Prepare selects the first undiscovered,
// unchecked target (or Exhausted), fully encodes the locale-aware presentation
// into epoch-bound scratch, and does not mutate discovery. Commit revalidates
// that exact armed selection and marks it discovered. Reload/replay or another
// epoch change clears the transient latch, so Commit fails and the owning
// handler applies its refund path. Cancel ends the repeated-message latch.
bool Rando_HintsPreparePaid(RandoHintPaidSource source);
bool Rando_HintsCommitPaid(RandoHintPaidSource source);
void Rando_HintsCancelPaid(RandoHintPaidSource source);
// Read-only availability probe used to frame paid service choices truthfully.
// It follows the same discovery/checked-target scan as Prepare but never arms
// presentation state or changes discovery.
bool Rando_HintsPaidHasClue(RandoHintPaidSource source);
// Set the source/price context for the next paid Yes/No prompt. The messaging
// post-decode hook uses it only when no clue is available, replacing the
// vanilla "tip/reading" claim with localized price + healing-only framing.
void Rando_HintsSetPaidPromptContext(RandoHintPaidSource source, uint16 price);

// Returns the stable dialogue label for a source with a primary assignment.
uint16 Rando_GetHintDialogueId(RandoHintNpc npc);

// Retrieve the complete human-readable PRIMARY hint text for compatibility
// spoiler output. Paid reserves are enumerated through Rando_GetHintFact.
const char *Rando_GetHintString(RandoHintNpc npc);

// Returns the ALTTPR-compatible string-ID for `npc` (e.g., `kRandoHintNpc_TeleEasternPalace`
// → `"telepathic_tile_eastern_palace"`). Used by the spoiler-JSON
// emitter to produce keys that diff cleanly against ALTTPR seeds.
// Returns NULL for invalid npc.
const char *Rando_GetHintNpcStringId(RandoHintNpc npc);

// Clear plan, discovery, imported expectation, and pending paid transactions.
void Rando_ClearHints(void);

// ---------------------------------------------------------------------------
// Telepathic-tile runtime dispatch.
//
// The 15 ALTTPR telepathic-tile hints surface in-game by hijacking the
// VANILLA per-room telepathic-tile dialogue ids. Link reading a tile sets
// `dialogue_message_index` (player.c::Link_PerformRead -> Dungeon_GetTeleMsg)
// to one of the 15 vanilla US tele-message ids; the messaging engine
// (messaging.c::Text_LoadCharacterBuffer) calls Rando_RenderHintMessage at
// its top to give this module first refusal on those ids.
//
// The 15 hint-bearing vanilla US tele-message ids are:
//   0xB4, 0xB5, 0xB8, 0xB9, 0xBA, 0xBB, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2,
//   0xC3, 0xC4, 0xC5, 0xC6
// (0xB4 is the Eastern Palace tile, the first ALTTPR tile; 0xC7 is the Chris
// Houlihan secret room and is NOT a hint tile. See kHintTileMsgIds in
// rando_hints.c for the off-by-one this corrects.) These ids map positionally
// to the 15
// RandoHintNpc telepathic-tile slots: each distinct physical tile shows one
// distinct generated hint. The exact tile<->hint pairing need not byte-match
// ALTTPR because ALTTPR itself fy_shuffles the tile list (HintService.php:59)
// — the generator's per-tile assignment is already a deterministic shuffle.
// ---------------------------------------------------------------------------

// True when `msg_id` is one of the 15 hint-bearing vanilla telepathic-tile
// message ids above (0xB4 the Eastern Palace tile IS included; 0xC7 the Chris
// Houlihan room is excluded). Pure predicate; does
// NOT consult the active hint table or rando-active state.
bool Rando_IsHintTileMessage(uint16 msg_id);

// Generated-hint and non-interactive vanilla-dialogue interception. Called at
// the very top of Text_LoadCharacterBuffer. Owned hint surfaces are always
// intercepted for an active randomizer slot: ready plans render the assigned
// fact, while Off/missing/unsupported/mismatch/exhausted states render truthful
// locale-aware neutral text. On true, writes font-encoded character codes
// (the messaging engine's `messaging_text_buffer`, >=256 bytes), laid out as
// up to three message-box lines and terminated with the 0x7f end marker the
// renderer expects, then resets `dialogue_msg_read_pos`. Returns false in
// every other case so the vanilla dialogue decode proceeds unchanged.
bool Rando_RenderHintMessage(uint16 msg_id, uint8 *out_buffer);

// Post-decode companion for choice surfaces. Stumpy/Flute Boy uses the same
// resolver/gates as Rando_RenderHintMessage and receives a hint/neutral page
// followed by its preserved choice. Current-schema paid services also use this
// hook when no clue is available, receiving localized no-clue + exact-price +
// healing-only framing before their preserved choice. Frozen schema 1 retains
// its original bytes. Returns false without modifying the buffer for
// non-owned/inapplicable messages.
bool Rando_RewriteInteractiveHintMessage(uint16 msg_id, uint8 *out_buffer);

// True when `msg_id` is a confirmed vanilla-dialogue redirect owned by the
// active slot and its context discriminator matches. Hints Off or unavailable
// identity still counts as owned because the surface renders neutral text
// rather than a false vanilla placement claim.
// Pure/read-only: it never renders or mutates the hint table/buffer.
// Used by both Rando_RenderHintMessage and story-dialogue fast-forward policy.
bool Rando_IsDynamicHintMessage(uint16 msg_id);

// Unrestricted spoiler-bearing dev diagnostic: dump live/expected/computed plan
// identity, discovery, assignments, queues, and text to dump_hints.txt even for
// a race slot (called from ZeldaDumpDebugState / F12). `cur_msg_id` is the
// current dialogue_message_index.
void Rando_DumpHintDebug(uint16 cur_msg_id);

// Full deterministic plan, exact-rendering, discovery, paid-queue,
// persistence-identity, locale-neutral, and redirect regression self-check.
void Hints_SelfCheck(void);

#endif  // ZELDA3_RANDO_HINTS_H_
