// rando_hints.h — Phase B Slice 5 (add-rando-hints) scaffold.
//
// Status: SCAFFOLD. Full hint-text generation (ALTTPR HintService.php +
// Text.php) is multi-week work; this header pins the API surface and
// dialogue-ID range so dependent code can compile + integrate against
// the contract. All getters return the "no hint" sentinel until the
// generator body lands.
//
// **Scope (per §57 translation status in design.md + fork extension decision)**:
//   - ALTTPR-equivalent core: 15 telepathic tiles
//     (`HintService.php:59-75`).
//   - ALTTPR-equivalent goal text: Murahdahla static per-goal text
//     line (`Randomizer.php:1029`), emitted only on
//     `goal == triforce-hunt`.
//   - **Fork extensions** (NOT in ALTTPR): Storyteller (the 20-rupee
//     Dark World tip NPC) + 3 Fortune Tellers (Kakariko, Dark World,
//     Lake Hylia). 4 extra hint slots. Sprite-handler hooks intercept
//     the existing dialogue path and substitute hint text. Improves
//     accessibility (more hint locations) without changing the
//     telepathic-tile core. Spoiler-JSON keys are prefixed `fork_` so
//     ALTTPR-diff-ability is preserved for the core 15+1.
//   - Bookshelf hint sources considered but dropped — poor
//     discoverability + thematic dilution of vanilla world-building.

#ifndef ZELDA3_RANDO_HINTS_H_
#define ZELDA3_RANDO_HINTS_H_

#include "../types.h"
#include "rando_placement.h"

// ---------------------------------------------------------------------------
// Hint-NPC id space.
//
// IDs 1-15: 15 telepathic tiles (ALTTPR `HintService.php:59-75`).
// ID 16   : Murahdahla static per-goal text (ALTTPR `Randomizer.php:1029`).
// IDs 17-20: zelda3-fork extensions (NOT in ALTTPR upstream). Improve
//           accessibility by routing existing in-game NPC dialogue
//           through the hint generator.
//
// Order is stable for spoiler-JSON keys; fork extensions use a
// `fork_` prefix on their string IDs so ALTTPR-diff-ability is
// preserved for the core 16 entries.
// ---------------------------------------------------------------------------
typedef enum RandoHintNpc {
  kRandoHintNpc_None = 0,

  // 15 telepathic tiles (ALTTPR `HintService.php:59-75`).
  kRandoHintNpc_TeleEasternPalace          = 1,
  kRandoHintNpc_TeleTowerOfHera_Floor4     = 2,
  kRandoHintNpc_TeleSpectacleRock          = 3,
  kRandoHintNpc_TeleSwampEntrance          = 4,
  kRandoHintNpc_TeleThievesTownUpstairs    = 5,
  kRandoHintNpc_TeleMiseryMire             = 6,
  kRandoHintNpc_TelePalaceOfDarkness       = 7,
  kRandoHintNpc_TeleDesertBonkTorchRoom    = 8,
  kRandoHintNpc_TeleCastleTower            = 9,
  kRandoHintNpc_TeleIceLargeRoom           = 10,
  kRandoHintNpc_TeleTurtleRock             = 11,
  kRandoHintNpc_TeleIceEntrace             = 12,  // [sic] ALTTPR typo preserved
  kRandoHintNpc_TeleIceStalfosKnightsRoom  = 13,
  kRandoHintNpc_TeleTowerOfHera_Entrance   = 14,
  kRandoHintNpc_TeleSouthEastDarkworldCave = 15,

  // Murahdahla — static per-goal text, only emitted on Triforce Hunt.
  // Not generated by HintService; lives at `Randomizer.php:1029`.
  kRandoHintNpc_Murahdahla                 = 16,

  // Fork extensions (NOT in ALTTPR). The Storyteller is the 20-rupee
  // health-restoring NPC `Sprite_28_DarkWorldHintNPC` — vanilla framing
  // ("I'll give you a tip for
  // 20 rupees") makes it a natural fit. The 3 Fortune Tellers are
  // currently near-useless cosmetic NPCs whose framing ("I see your
  // future") matches hint-distribution.
  kRandoHintNpc_ForkStoryteller            = 17,
  kRandoHintNpc_ForkFortuneTellerKak       = 18,
  kRandoHintNpc_ForkFortuneTellerDark      = 19,
  kRandoHintNpc_ForkFortuneTellerLakeHylia = 20,

  kRandoHintNpc__Count                     = 21,
} RandoHintNpc;

// ---------------------------------------------------------------------------
// Settings axis: hints on/off (binary, matching ALTTPR `spoil.Hints` at
// `HintService.php:54` which tests `=== 'on'`).
//
// Bit width reserved in canonical serialization: 2 bits (room for future
// modes if needed — currently only on/off are wired). Canonical-
// serialization landing is a Slice 5 follow-up tied to the actual
// generator body; scaffold does NOT extend the canonical bytes yet.
// ---------------------------------------------------------------------------
typedef enum RandoHintsMode {
  kHintsMode_Off = 0,
  kHintsMode_On  = 1,
} RandoHintsMode;

// ---------------------------------------------------------------------------
// Dialogue-ID carve — Phase B Slice 5 §57.3.
//
// Vanilla zelda3 dialogue IDs (16-bit, `dialogue_message_index`) max out at
// 0x18a per highest assigned vanilla site. Carve `0x200..0x213` for the hint
// range — 20 IDs, positionally mapped:
//   id = kRandoHintDialogueBase + (RandoHintNpc - 1)
// The runtime intercept lives at `Text_LoadCharacterBuffer`;
// when the request id falls in the carve,
// the text source switches from `g_zenv.dialogue_blk` to the in-memory
// hint table populated by `Rando_GenerateHints`.
// ---------------------------------------------------------------------------
#define kRandoHintDialogueBase  0x200u
#define kRandoHintDialogueCount 20u  // = kRandoHintNpc__Count - 1
#define kRandoHintDialogueEnd   (kRandoHintDialogueBase + kRandoHintDialogueCount)

// Returns true if `dialogue_id` is in the rando hint range. Used by the
// text-engine intercept to switch source from asset-blob to hint table.
static inline bool Rando_DialogueIdIsHint(uint16 dialogue_id) {
  return dialogue_id >= kRandoHintDialogueBase &&
         dialogue_id < kRandoHintDialogueEnd;
}

// Maps a vanilla dialogue ID to the rando dialogue ID when this slot has
// a hint allocated for the corresponding NPC. Used by sprite-handler
// wrappers (e.g., the telepathic-tile read path in `player.c::Link_PerformRead`)
// to redirect the dialogue lookup when `Rando_GetHintDialogueId(npc)`
// returns a non-sentinel value.
//
// STUB: until the generator + per-tile mapping table land, this returns
// `vanilla_id` unchanged (no remapping).
//
// `room_or_area` distinguishes overworld screens (`is_overworld=true`)
// from indoor dungeon rooms (`is_overworld=false`). Each ALTTPR
// telepathic-tile string-ID corresponds to a unique (area, vanilla_id)
// pair that the per-tile table maps to a `RandoHintNpc`.
uint16 Rando_RemapTeleMsg(uint16 vanilla_id, uint16 room_or_area, bool is_overworld);

// Generate the per-slot hint set. Stub today.
//
// Real impl (per §57.2): 5-step algorithm — GT-BK conditional, Boots
// always, 5 from a fixed 10-entry pool, ≤4 advancement-item hints,
// fill with random hints + joke fallback. Deterministic from
// (settings, seed_u64) via a sub-RNG seeded at slot generate time.
// Sphere data is accepted for forward-compat but unused upstream.
bool Rando_GenerateHints(const RandoSettings *settings,
                         const RandoPlacementTable *placements,
                         const RandoSpheres *spheres);

// Returns the dynamic dialogue ID allocated for `npc` in the active
// slot. Returns `0xFFFF` when no hint is allocated (caller falls back
// to vanilla). STUB returns `0xFFFF`.
uint16 Rando_GetHintDialogueId(RandoHintNpc npc);

// Retrieve the human-readable hint text for `npc` for spoiler emission.
// Returns NULL when no hint is allocated (stub: always NULL).
const char *Rando_GetHintString(RandoHintNpc npc);

// Returns the ALTTPR-compatible string-ID for `npc` (e.g., `kRandoHintNpc_TeleEasternPalace`
// → `"telepathic_tile_eastern_palace"`). Used by the spoiler-JSON
// emitter to produce keys that diff cleanly against ALTTPR seeds.
// Returns NULL for invalid npc.
const char *Rando_GetHintNpcStringId(RandoHintNpc npc);

// Clear the active hint set (called from `Rando_DeactivateSlot`).
void Rando_ClearHints(void);

// ---------------------------------------------------------------------------
// Telepathic-tile runtime dispatch (Phase B Slice 5 §57.3 wiring).
//
// The 15 ALTTPR telepathic-tile hints surface in-game by hijacking the
// VANILLA per-room telepathic-tile dialogue ids. Link reading a tile sets
// `dialogue_message_index` (player.c::Link_PerformRead -> Dungeon_GetTeleMsg)
// to one of the 15 vanilla US tele-message ids; the messaging engine
// (messaging.c::Text_LoadCharacterBuffer) calls Rando_RenderHintMessage at
// its top to give this module first refusal on those ids.
//
// The 15 hint-bearing vanilla US tele-message ids are:
//   0xB5, 0xB8, 0xB9, 0xBA, 0xBB, 0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3,
//   0xC4, 0xC5, 0xC6, 0xC7
// (0xB4 is the GENERIC default tele text used as filler in many rooms and is
// intentionally NOT a hint tile.) These ids map positionally to the 15
// RandoHintNpc telepathic-tile slots: each distinct physical tile shows one
// distinct generated hint. The exact tile<->hint pairing need not byte-match
// ALTTPR because ALTTPR itself fy_shuffles the tile list (HintService.php:59)
// — the generator's per-tile assignment is already a deterministic shuffle.
// ---------------------------------------------------------------------------

// True when `msg_id` is one of the 15 hint-bearing vanilla telepathic-tile
// message ids above (0xB4 generic-default excluded). Pure predicate; does
// NOT consult the active hint table or rando-active state.
bool Rando_IsHintTileMessage(uint16 msg_id);

// Telepathic-tile dialogue interception. Called at the very top of
// Text_LoadCharacterBuffer. Returns true (and fills `out_buffer`) only when
// ALL of: the randomizer slot is active, the active hint table has a hint for
// the tile `msg_id` maps to, and `msg_id` is a hint-tile id. On true, writes
// the generated hint's font-encoded character codes into `out_buffer`
// (the messaging engine's `messaging_text_buffer`, >=256 bytes), laid out as
// up to three message-box lines and terminated with the 0x7f end marker the
// renderer expects, then resets `dialogue_msg_read_pos`. Returns false in
// every other case so the vanilla dialogue decode proceeds unchanged.
bool Rando_RenderHintMessage(uint16 msg_id, uint8 *out_buffer);

// Self-check (called from Rando_RunAllSelfChecks). Asserts that
// Rando_GenerateHints produces byte-identical output across consecutive
// invocations with the same inputs (determinism contract per the
// header of rando_hints.c) and exercises the kHintsMode_Off / NULL-args
// defensive paths.
void Hints_SelfCheck(void);

#endif  // ZELDA3_RANDO_HINTS_H_
