// shuffle_entrance.c — Phase C entrance shuffle, Stage 1. See header.
#include "shuffle_entrance.h"

#include "rando_logic.h"   // Rando_FindRegionByName, Rando_*EntranceRegionOverride*, RandoLocationDef
#include "rando_rng.h"     // RandoRng, Rng_SeedFromU64, Rng_NextRange
#include "rando_settings.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>

// kRandoLocations / kRandoLocationsCount are the generated logic location table
// (logic_data.c). Used only by the self-check's registry↔logic cross-validation.
extern const RandoLocationDef kRandoLocations[];
extern const uint32 kRandoLocationsCount;
// The static region-graph edge table — used by the dungeon self-check to confirm
// each dungeon's entry region is the destination of exactly one door-edge.
extern const RandoEdgeDef kRandoEdges[];
extern const uint32 kRandoEdgesCount;

// ---------------------------------------------------------------------------
// Static cave-interior table — the data home for cave shuffle.
// === GENERATED by assets/scripts/gen_entrance_table.py from
//     assets/rando/entrance_registry.yaml — do not hand-edit the numeric ids;
//     re-run the script and paste the block below. ===
// ---------------------------------------------------------------------------
typedef struct RandoCaveInterior {
  const char *name;            // interior_id (stable; for the spoiler)
  uint16 room;                 // 0x1xx (cached-exit class [0x100,0x180)\{0x104})
  const char *region_name;     // vanilla logic region of the door (resolved at
                               // runtime via Rando_FindRegionByName; NULL = none)
  const uint8 *entrance_ids;   // overworld entrance-ids that load this interior
  uint8 entrance_count;
  const uint16 *location_ids;  // member locations (NULL when none)
  uint8 location_count;
} RandoCaveInterior;

static const uint8 kEnt_ids_0[1] = { 0x3C };
static const uint8 kEnt_ids_1[2] = { 0x3E, 0x3F };
static const uint8 kEnt_ids_2[1] = { 0x40 };
static const uint8 kEnt_ids_3[3] = { 0x42, 0x43, 0x44 };
static const uint8 kEnt_ids_4[1] = { 0x45 };
static const uint8 kEnt_ids_5[2] = { 0x49, 0x4A };
static const uint8 kEnt_ids_6[1] = { 0x4B };
static const uint8 kEnt_ids_7[1] = { 0x4C };
static const uint8 kEnt_ids_8[2] = { 0x47, 0x48 };
static const uint8 kEnt_ids_9[2] = { 0x53, 0x54 };
static const uint8 kEnt_ids_10[1] = { 0x4D };
static const uint8 kEnt_ids_11[1] = { 0x4E };
static const uint8 kEnt_ids_12[2] = { 0x56, 0x84 };
static const uint8 kEnt_ids_13[1] = { 0x6C };
static const uint8 kEnt_ids_14[2] = { 0x4F, 0x50 };
static const uint8 kEnt_ids_15[1] = { 0x41 };
static const uint8 kEnt_ids_16[1] = { 0x5F };
static const uint8 kEnt_ids_17[2] = { 0x3D, 0x55 };
static const uint8 kEnt_ids_18[1] = { 0x5B };
static const uint8 kEnt_ids_19[2] = { 0x6D, 0x6E };
static const uint8 kEnt_ids_20[1] = { 0x57 };
static const uint8 kEnt_ids_21[2] = { 0x58, 0x5A };
static const uint8 kEnt_ids_22[1] = { 0x59 };
static const uint8 kEnt_ids_23[1] = { 0x60 };
static const uint8 kEnt_ids_24[2] = { 0x5C, 0x62 };
static const uint8 kEnt_ids_25[2] = { 0x5D, 0x5E };
static const uint8 kEnt_ids_26[1] = { 0x63 };
static const uint8 kEnt_ids_27[1] = { 0x67 };
static const uint8 kEnt_ids_28[1] = { 0x61 };
static const uint8 kEnt_ids_29[1] = { 0x68 };
static const uint8 kEnt_ids_30[2] = { 0x51, 0x52 };
static const uint8 kEnt_ids_31[2] = { 0x46, 0x6B };
static const uint8 kEnt_ids_32[1] = { 0x64 };
static const uint8 kEnt_ids_33[2] = { 0x65, 0x66 };
static const uint8 kEnt_ids_34[2] = { 0x69, 0x6A };
static const uint8 kEnt_ids_35[2] = { 0x6F, 0x70 };
static const uint8 kEnt_ids_36[2] = { 0x71, 0x72 };
static const uint8 kEnt_ids_37[1] = { 0x83 };

static const uint16 kEnt_locs_2[1] = { 168 };
static const uint16 kEnt_locs_3[1] = { 153 };
static const uint16 kEnt_locs_4[3] = { 142, 143, 144 };
static const uint16 kEnt_locs_6[1] = { 154 };
static const uint16 kEnt_locs_7[1] = { 147 };
static const uint16 kEnt_locs_8[1] = { 215 };
static const uint16 kEnt_locs_9[1] = { 216 };
static const uint16 kEnt_locs_10[1] = { 175 };
static const uint16 kEnt_locs_11[1] = { 173 };
static const uint16 kEnt_locs_12[1] = { 180 };
static const uint16 kEnt_locs_13[5] = { 176, 177, 178, 179, 185 };
static const uint16 kEnt_locs_14[1] = { 197 };
static const uint16 kEnt_locs_15[1] = { 229 };
static const uint16 kEnt_locs_16[2] = { 206, 207 };
static const uint16 kEnt_locs_17[5] = { 222, 223, 224, 225, 227 };
static const uint16 kEnt_locs_18[1] = { 152 };
static const uint16 kEnt_locs_19[1] = { 165 };

#define kEntranceCaveInteriorCount 38
static const RandoCaveInterior kCaveInteriors[kEntranceCaveInteriorCount] = {
  { /* 0*/ "treasure_shell_game", 0x100, "LightWorld_NorthWest", kEnt_ids_0, 1, 0, 0 },
  { /* 1*/ "snitch_house", 0x101, "LightWorld_NorthWest", kEnt_ids_1, 2, 0, 0 },
  { /* 2*/ "sickboy_house", 0x102, "LightWorld_NorthWest", kEnt_ids_2, 1, kEnt_locs_2, 1 },
  { /* 3*/ "kakariko_tavern", 0x103, "LightWorld_NorthWest", kEnt_ids_3, 3, kEnt_locs_3, 1 },
  { /* 4*/ "sahasrahla_hut", 0x105, "LightWorld_NorthEast", kEnt_ids_4, 1, kEnt_locs_4, 3 },
  { /* 5*/ "kakariko_library", 0x107, "LightWorld_South", kEnt_ids_5, 2, 0, 0 },
  { /* 6*/ "chicken_house", 0x108, "LightWorld_NorthWest", kEnt_ids_6, 1, kEnt_locs_6, 1 },
  { /* 7*/ "potion_shop", 0x109, "LightWorld_NorthEast", kEnt_ids_7, 1, kEnt_locs_7, 1 },
  { /* 8*/ "village_chest_game", 0x106, "DarkWorld_NorthWest", kEnt_ids_8, 2, kEnt_locs_8, 1 },
  { /* 9*/ "bomb_shop", 0x11C, "DarkWorld_NorthWest", kEnt_ids_9, 2, kEnt_locs_9, 1 },
  { /*10*/ "aginah_cave", 0x10A, "LightWorld_South", kEnt_ids_10, 1, kEnt_locs_10, 1 },
  { /*11*/ "watergate", 0x10B, "LightWorld_South", kEnt_ids_11, 1, kEnt_locs_11, 1 },
  { /*12*/ "ice_rod_cave", 0x120, "LightWorld_South", kEnt_ids_12, 2, kEnt_locs_12, 1 },
  { /*13*/ "mini_moldorm_cave", 0x123, "LightWorld_South", kEnt_ids_13, 1, kEnt_locs_13, 5 },
  { /*14*/ "mimic_cave", 0x10C, "LightWorld_DeathMountain_East", kEnt_ids_14, 2, kEnt_locs_14, 1 },
  { /*15*/ "byrna_gauntlet", 0x117, "DarkWorld_DeathMountain_West", kEnt_ids_15, 1, kEnt_locs_15, 1 },
  { /*16*/ "mire_shed", 0x10D, "DarkWorld_Mire", kEnt_ids_16, 1, kEnt_locs_16, 2 },
  { /*17*/ "hype_cave", 0x11E, "DarkWorld_South", kEnt_ids_17, 2, kEnt_locs_17, 5 },
  { /*18*/ "hall_of_invisibility_cape", 0x113, "LightWorld_NorthWest", kEnt_ids_18, 1, kEnt_locs_18, 1 },
  { /*19*/ "thief_hideout", 0x124, "LightWorld_NorthWest", kEnt_ids_19, 2, kEnt_locs_19, 1 },
  { /*20*/ "general_store_1", 0x110, "LightWorld_NorthWest", kEnt_ids_20, 1, 0, 0 },
  { /*21*/ "general_store_2", 0x112, "LightWorld_NorthWest", kEnt_ids_21, 2, 0, 0 },
  { /*22*/ "archery_game", 0x111, "DarkWorld_South", kEnt_ids_22, 1, 0, 0 },
  { /*23*/ "general_store_3", 0x10F, "DarkWorld_NorthWest", kEnt_ids_23, 1, 0, 0 },
  { /*24*/ "pond_of_wishing", 0x114, "LightWorld_NorthEast", kEnt_ids_24, 2, 0, 0 },
  { /*25*/ "pond_of_happiness", 0x115, "LightWorld_South", kEnt_ids_25, 2, 0, 0 },
  { /*26*/ "warped_pond_of_wishing", 0x116, "DarkWorld_NorthWest", kEnt_ids_26, 1, 0, 0 },
  { /*27*/ "chest_shell_game", 0x118, "LightWorld_NorthWest", kEnt_ids_27, 1, 0, 0 },
  { /*28*/ "blinds_old_hideout", 0x119, "DarkWorld_NorthWest", kEnt_ids_28, 1, 0, 0 },
  { /*29*/ "storyteller_cave_4", 0x11A, "DarkWorld_NorthEast", kEnt_ids_29, 1, 0, 0 },
  { /*30*/ "refill_cave_1", 0x11B, "LightWorld_NorthEast", kEnt_ids_30, 2, 0, 0 },
  { /*31*/ "kakariko_lame_shop", 0x11F, "LightWorld_NorthWest", kEnt_ids_31, 2, 0, 0 },
  { /*32*/ "chez_smithies", 0x121, "LightWorld_NorthWest", kEnt_ids_32, 1, 0, 0 },
  { /*33*/ "fortune_teller", 0x122, "LightWorld_NorthWest", kEnt_ids_33, 2, 0, 0 },
  { /*34*/ "storyteller_cave_5", 0x10E, "DarkWorld_NorthEast", kEnt_ids_34, 2, 0, 0 },
  { /*35*/ "thief_hideout_3", 0x125, "LightWorld_NorthWest", kEnt_ids_35, 2, 0, 0 },
  { /*36*/ "fairy_cave_5", 0x126, "LightWorld_NorthWest", kEnt_ids_36, 2, 0, 0 },
  { /*37*/ "heart_piece_cave_3", 0x127, "LightWorld_DeathMountain_West", kEnt_ids_37, 1, 0, 0 },
};
// === end generated block ===

// ---------------------------------------------------------------------------
// Dungeon table (Stage 2) — the 6 cleanly single-overworld-entrance dungeons.
// Each entry_region is the to_region of exactly one door-edge in kRandoEdges, so
// the per-seed EDGE overlay (rando_logic.c) can swap door destinations by that
// key. From assets/rando/entrance_registry.yaml `dungeons:`. Eastern Palace
// (2-region), Skull Woods / Desert (multi-entrance), Misery Mire / Turtle Rock
// (medallion) and Ganon's Tower (goal) are deferred — see that file.
typedef struct RandoDungeon {
  const char *name;
  const char *entry_region_name;  // logic region resolved via Rando_FindRegionByName.
                                  // Used for cross-POOL eligibility (inbound-edge
                                  // count) + the approach analysis. For the medallion
                                  // dungeons this is the pre-door waypoint (e.g.
                                  // TurtleRock_Entrance), reached via the approaches.
  uint16 room;                    // entry room (< 0x100)
  uint8 entrance_id;              // overworld front-door entrance-id
  // The INTERIOR (lobby) region: the to_region of the dungeon's GATED door edge —
  // the region where the dungeon's locations live. The edge-override keys on THIS
  // so the door edge (and its predicate) is what gets remapped, tying any door gate
  // (e.g. MM/TR's medallion, on Entrance→Lobby) to the overworld SPOT rather than
  // the loaded interior (audit task 2.8). NULL ⇒ single-region dungeon whose entry
  // region IS its lobby (the registry region is already the door-edge target), so
  // the override key falls back to entry_region_name with no behavior change.
  const char *interior_region_name;
} RandoDungeon;

// The edge-override KEY for a dungeon: its interior (lobby) region, falling back to
// the entry region for single-region dungeons. See RandoDungeon.interior_region_name.
static const char *dungeon_override_key(const RandoDungeon *d) {
  return d->interior_region_name ? d->interior_region_name : d->entry_region_name;
}

// kEntranceDungeonCount is the FULL table size. The active SHUFFLE pool is the
// first kEntranceDungeonBaseCount (10) entries by default; Ganon's Tower (the
// last entry) joins only when the advanced shuffle_ganons_tower_entrance axis is
// on (see Entrance_DungeonPoolCount). GT MUST stay last so excluding it = taking
// the first 10.
#define kEntranceDungeonBaseCount 10
#define kEntranceDungeonCount 11
static const RandoDungeon kDungeons[kEntranceDungeonCount] = {
  { "palace_of_darkness",   "PalaceOfDarkness",     0x04A, 0x26 },
  { "swamp_palace",         "SwampPalace",          0x028, 0x25 },
  { "thieves_town",         "ThievesTown",          0x0DB, 0x34 },
  { "ice_palace",           "IcePalace_Lobby",      0x00E, 0x2D },
  { "tower_of_hera",        "TowerOfHera_Lobby",    0x077, 0x33 },
  { "hyrule_castle_tower",  "HyruleCastleTower",    0x0E0, 0x24 },
  // Eastern Palace — single overworld door (id 0x08 → room 0xC9). Its locations
  // all live in EasternPalace_Lobby (9) + EasternPalace_PastArmos (10, child of
  // 9), reached via the one door-edge 0x11→9. Region 8 ("EasternPalace") is an
  // empty/vestigial structural region (no locations, no outbound edges), so EP's
  // real entry region is the Lobby (9) and it fits the single-region model. The
  // earlier "2-region defer" was based on the YAML name, not the actual binding.
  // Misery Mire — single overworld door (id 0x27 → room 0x98), single entry
  // region (MiseryMire_Entrance, one inbound edge 0x02→0x16). Its medallion gate
  // lives in that door-edge predicate, which the override keeps with the door —
  // ALTTPR-consistent (you tap MM's tablet at MM's overworld spot regardless of
  // what's behind the door). Turtle Rock / Ganon's Tower stay deferred (multi-
  // entrance + goal/crystal); Eastern Palace deferred (2 entry regions).
  { "misery_mire",          "MiseryMire_Entrance",  0x098, 0x27, "MiseryMire_Lobby" },
  { "eastern_palace",       "EasternPalace_Lobby",  0x0C9, 0x08 },
  // Multi-entrance dungeons, MAIN door only — the extra doors are "contained"
  // (they lead back into the same dungeon), so leaving them vanilla while
  // shuffling just the front door is safe: the dungeon stays reachable via its
  // own side doors (the logic merely treats that as a conservative extra, never
  // claiming more than runtime → no softlock), and only the main door is in the
  // shuffle table so the side doors keep vanilla coupling.
  //  - Desert Palace: main 0x09; East 0x0A / West 0x0B / Boss 0x0C stay vanilla.
  //  - Turtle Rock: main 0x35; mountainface doors stay vanilla. Entry region
  //    TurtleRock_Entrance(29) has TWO inbound edges (LW+DW Death Mountain) — the
  //    override remaps both; medallion gate lives in the door predicate (kept).
  { "desert_palace",        "DesertPalace_Lobby",   0x084, 0x09 },
  { "turtle_rock",          "TurtleRock_Entrance",  0x0D6, 0x35, "TurtleRock_Lobby" },
  // Ganon's Tower — MUST be the LAST entry (index 10). Joins the pool only via
  // the advanced shuffle_ganons_tower_entrance opt-in. GT's crystal-tower gate
  // lives in its door-edge predicate, so under the shuffle it gates whatever
  // lands behind GT's door behind crystals.tower crystals; at high crystals that
  // can be circular (the door needs N crystals but leads to a crystal-bearing
  // dungeon that GIVES one). The full-reachability retry gate rejects circular
  // permutations, so such a seed simply fails to generate — lower crystals.tower
  // (0 always works) or reroll. Skull Woods stays deferred (truly multi-entrance).
  { "ganons_tower",         "GanonsTower_Lobby",    0x00C, 0x37 },
};

// Active dungeon shuffle-pool size for these settings: the base 10, plus Ganon's
// Tower when the advanced opt-in is on (and dungeon shuffle is active).
static int Entrance_DungeonPoolCount(const RandoSettings *settings) {
  if (settings != NULL && settings->shuffle_ganons_tower_entrance &&
      Entrance_IsDungeonActive(settings)) {
    return kEntranceDungeonCount;       // 11 (includes GT)
  }
  return kEntranceDungeonBaseCount;     // 10 (GT excluded)
}

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

bool Entrance_IsActive(const RandoSettings *settings) {
  if (settings == NULL) return false;
  if (!settings->shuffle_cave_entrances) return false;
  // Stage 1 supports cave shuffle on Open/Standard only. Inverted carries a
  // static per-location region override the per-seed override would clobber;
  // Retro re-uses several cave host-rooms for TakeAny. Both deferred.
  if (settings->world_state != kWorldState_Open &&
      settings->world_state != kWorldState_Standard) {
    return false;
  }
  return true;
}

// Map a raw entrance-id to its cave-interior index, or -1 if not a cave.
static int interior_of_entrance(uint8 ent_id) {
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
      if (kCaveInteriors[i].entrance_ids[k] == ent_id) return i;
    }
  }
  return -1;
}

int Entrance_ComputePermutation(const RandoSettings *settings, uint64 seed,
                                uint8 attempt,
                                uint8 assign[kEntranceMaxInteriors]) {
  if (assign == NULL || !Entrance_IsActive(settings)) return 0;
  const int n = kEntranceCaveInteriorCount;
  for (int i = 0; i < n; i++) assign[i] = (uint8)i;

  RandoRng rng;
  // Mix the attempt index into the seed (same constant the placer uses to
  // perturb its retry seed) so each retry draws a distinct permutation while
  // attempt 0 is a pure function of the seed (single-seed determinism).
  Rng_SeedFromU64(&rng, seed ^ ((uint64)attempt * 0x9E3779B97F4A7C15ull));
  // Fisher–Yates over the interior indices (coupled = one bijection).
  for (int i = n - 1; i > 0; i--) {
    uint32 j = Rng_NextRange(&rng, (uint32)(i + 1));
    uint8 t = assign[i]; assign[i] = assign[j]; assign[j] = t;
  }
  return n;
}

void Entrance_ApplyRegionOverrides(const uint8 *assign, int n) {
  Rando_BeginEntranceRegionOverrides();
  if (assign == NULL) return;
  // Audit M3 — clamp the loop bound to the static table (this is a public entry
  // point; the `assign[ix]` value is already range-checked below, but the `ix`
  // index into kCaveInteriors[] must be bounded too).
  if (n > kEntranceCaveInteriorCount) n = kEntranceCaveInteriorCount;
  // For each interior ix (door fixed in vanilla region R[ix]), the interior now
  // reached through ix's door is J = assign[ix]; J's locations become reachable
  // via R[ix]. So override every location of interior J with interior ix's
  // region. assign is a bijection ⇒ each interior's locations are set once.
  for (int ix = 0; ix < n; ix++) {
    const RandoCaveInterior *src = &kCaveInteriors[ix];
    if (src->region_name == NULL) continue;
    uint16 region_id = Rando_FindRegionByName(src->region_name);
    if (region_id == 0xFFFF) continue;  // unknown region name — skip (no-op)
    int j = assign[ix];
    if (j < 0 || j >= kEntranceCaveInteriorCount) continue;
    const RandoCaveInterior *dst = &kCaveInteriors[j];
    for (int k = 0; k < dst->location_count; k++) {
      Rando_SetEntranceRegionOverride(dst->location_ids[k], region_id);
    }
  }
}

void Entrance_ClearRegionOverrides(void) {
  Rando_ClearEntranceRegionOverrides();
}

void Entrance_BuildDoorOverlay(const uint8 *assign, int n,
                               const uint8 *vanilla, uint32 len,
                               uint8 *overlay) {
  if (vanilla == NULL || overlay == NULL) return;
  memcpy(overlay, vanilla, len);     // copy first (so a NULL assign = identity)
  if (assign == NULL) return;
  for (uint32 d = 0; d < len; d++) {
    int i = interior_of_entrance(vanilla[d]);
    if (i < 0) continue;                 // not a cave door — leave unchanged
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) continue;
    // The door for interior i now loads interior j; write j's representative
    // (first) entrance-id. Coupling is handled by the engine's entry caching.
    overlay[d] = kCaveInteriors[j].entrance_ids[0];
  }
  (void)n;
}

// ---------------------------------------------------------------------------
// Dungeon engine (Stage 2)
// ---------------------------------------------------------------------------

// Map a raw entrance-id to its dungeon index within the first `count` dungeons
// (the active pool), or -1 if not present. Bounding by `count` keeps Ganon's
// Tower (the last entry) untouched when its opt-in is off.
static int dungeon_of_entrance(uint8 ent_id, int count) {
  if (count > kEntranceDungeonCount) count = kEntranceDungeonCount;
  for (int i = 0; i < count; i++) {
    if (kDungeons[i].entrance_id == ent_id) return i;
  }
  return -1;
}

bool Entrance_IsDungeonActive(const RandoSettings *settings) {
  if (settings == NULL) return false;
  if (!settings->shuffle_dungeon_entrances) return false;
  // Same world-state scope as caves (Open/Standard).
  if (settings->world_state != kWorldState_Open &&
      settings->world_state != kWorldState_Standard) {
    return false;
  }
  return true;
}

int Entrance_ComputeDungeonPermutation(const RandoSettings *settings, uint64 seed,
                                       uint8 attempt,
                                       uint8 assign[kEntranceMaxInteriors]) {
  if (assign == NULL || !Entrance_IsDungeonActive(settings)) return 0;
  const int n = Entrance_DungeonPoolCount(settings);  // 10, or 11 with GT opt-in
  for (int i = 0; i < n; i++) assign[i] = (uint8)i;
  RandoRng rng;
  // Distinct salt from the cave RNG so cave and dungeon permutations are
  // independent when both axes are on (both still deterministic in
  // (seed, attempt) for save→regen).
  Rng_SeedFromU64(&rng, (seed ^ 0xD0D0D0D0D0D0D0D0ull) ^
                            ((uint64)attempt * 0x9E3779B97F4A7C15ull));
  for (int i = n - 1; i > 0; i--) {
    uint32 j = Rng_NextRange(&rng, (uint32)(i + 1));
    uint8 t = assign[i]; assign[i] = assign[j]; assign[j] = t;
  }
  return n;
}

void Entrance_ApplyEdgeOverrides(const uint8 *assign, int n) {
  Rando_BeginEntranceEdgeOverrides();
  if (assign == NULL) return;
  if (n > kEntranceDungeonCount) n = kEntranceDungeonCount;
  // Dungeon ix's door now leads to dungeon assign[ix]. The GATED door-edge whose
  // destination is ix's interior (lobby) region must now land at assign[ix]'s
  // interior region — keyed by the interior region so the door edge AND its gate
  // (e.g. MM/TR's medallion, which sits on Entrance→Lobby) move with the SOURCE
  // spot, not the loaded interior (task 2.8). For single-region dungeons the
  // interior key == entry region, so this is byte-identical to the old behavior.
  for (int ix = 0; ix < n; ix++) {
    uint16 from_lobby = Rando_FindRegionByName(dungeon_override_key(&kDungeons[ix]));
    int j = assign[ix];
    if (j < 0 || j >= kEntranceDungeonCount) continue;
    uint16 to_lobby = Rando_FindRegionByName(dungeon_override_key(&kDungeons[j]));
    if (from_lobby == 0xFFFF || to_lobby == 0xFFFF) continue;
    Rando_SetEntranceEdgeOverride(from_lobby, to_lobby);
  }
}

void Entrance_ClearEdgeOverrides(void) {
  Rando_ClearEntranceEdgeOverrides();
}

void Entrance_RemapDungeonDoors(const uint8 *assign, int n,
                                uint8 *overlay, uint32 len) {
  if (overlay == NULL || assign == NULL) return;
  if (n > kEntranceDungeonCount) n = kEntranceDungeonCount;
  // overlay holds vanilla dungeon entrance-ids here (the cave pass never touches
  // dungeon slots — the two id sets are disjoint). Redirect each dungeon door to
  // its image's entrance-id.
  for (uint32 d = 0; d < len; d++) {
    int i = dungeon_of_entrance(overlay[d], n);  // only the active pool [0,n)
    if (i < 0) continue;
    int j = assign[i];
    if (j < 0 || j >= n) continue;
    overlay[d] = kDungeons[j].entrance_id;
  }
}

// Coupling helper: given a SOURCE door's vanilla dungeon entrance-id, return the
// room the room-keyed exit search should target so the player returns to that
// SOURCE door (not the loaded dungeon's vanilla door). Returns 0 if the id is
// not a v1 dungeon door.
uint16 Entrance_DungeonSourceExitRoom(uint8 vanilla_entrance_id) {
  // Full table here (incl. GT): this is only consulted for a door the overlay
  // actually redirected, so an inactive GT door never reaches it (its caller
  // bails when the overlay value still equals vanilla).
  int i = dungeon_of_entrance(vanilla_entrance_id, kEntranceDungeonCount);
  if (i < 0) return 0;
  return kDungeons[i].room;
}

// ---------------------------------------------------------------------------
// Cross-category engine (Stage 3 / Crossed) — caves + dungeons in ONE pool.
// See design.md §9. Endpoint index space: e < kEntranceCaveInteriorCount is
// cave[e]; otherwise it's the (e - kEntranceCaveInteriorCount)-th CROSS-ELIGIBLE
// dungeon (single-inbound-edge dungeons only; TR/GT excluded — multi-source ⇒
// ambiguous predicate to inherit). assign[e] = the endpoint now behind e's door.
// ---------------------------------------------------------------------------
#define kCrossVoidRegion 63  // unreachable sink: removes a dungeon's original
                             // door-edge when a cave lands behind it. Safe:
                             // 63 < kReachabilityMaxRegions(256); no locs/edges.

// Fill `idx` with the kDungeons indices that are cross-eligible (entry region is
// the destination of EXACTLY ONE door-edge). Stable table order. Returns count.
static int cross_dungeon_list(uint8 idx[kEntranceDungeonCount]) {
  int n = 0;
  for (int i = 0; i < kEntranceDungeonCount; i++) {
    uint16 rid = Rando_FindRegionByName(kDungeons[i].entry_region_name);
    if (rid == 0xFFFF) continue;
    int inbound = 0;
    for (uint32 e = 0; e < kRandoEdgesCount; e++)
      if (kRandoEdges[e].to_region == rid) inbound++;
    if (inbound == 1) idx[n++] = (uint8)i;
  }
  return n;
}

// A dungeon's single door-edge: its from_region + predicate (offset/len). Only
// valid for cross-eligible (single-edge) dungeons.
static bool dungeon_door_edge(uint16 entry_region, uint16 *from,
                              uint32 *pred_off, uint16 *pred_len) {
  for (uint32 e = 0; e < kRandoEdgesCount; e++) {
    if (kRandoEdges[e].to_region == entry_region) {
      *from = kRandoEdges[e].from_region;
      *pred_off = kRandoEdges[e].predicate_offset;
      *pred_len = kRandoEdges[e].predicate_length;
      return true;
    }
  }
  return false;
}

bool Entrance_IsCrossActive(const RandoSettings *settings) {
  if (settings == NULL || !settings->cross_category) return false;
  // Cross is the "mix caves + dungeons" master mode; the Crossed preset sets
  // cave + dungeon + cross together. Open/Standard only (same as the others).
  if (!settings->shuffle_cave_entrances || !settings->shuffle_dungeon_entrances)
    return false;
  return settings->world_state == kWorldState_Open ||
         settings->world_state == kWorldState_Standard;
}

// Combined-pool size = caves + cross-eligible dungeons.
static int cross_pool_count(void) {
  uint8 didx[kEntranceDungeonCount];
  return kEntranceCaveInteriorCount + cross_dungeon_list(didx);
}

int Entrance_ComputeCrossPermutation(const RandoSettings *settings, uint64 seed,
                                     uint8 attempt, uint8 assign[kEntranceMaxInteriors]) {
  if (assign == NULL || !Entrance_IsCrossActive(settings)) return 0;
  int n = cross_pool_count();
  if (n > kEntranceMaxInteriors) return 0;  // safety (47 << 64)
  for (int i = 0; i < n; i++) assign[i] = (uint8)i;
  RandoRng rng;
  Rng_SeedFromU64(&rng, (seed ^ 0xC2055CA7E5C2055Cull) ^
                            ((uint64)attempt * 0x9E3779B97F4A7C15ull));
  for (int i = n - 1; i > 0; i--) {
    uint32 j = Rng_NextRange(&rng, (uint32)(i + 1));
    uint8 t = assign[i]; assign[i] = assign[j]; assign[j] = t;
  }
  return n;
}

// Install the 4-case cross-class overrides from the combined permutation.
void Entrance_ApplyCrossOverrides(const uint8 *assign, int n) {
  Rando_BeginEntranceRegionOverrides();
  Rando_BeginEntranceEdgeOverrides();
  if (assign == NULL) return;
  uint8 didx[kEntranceDungeonCount];
  int ndun = cross_dungeon_list(didx);
  const int ncave = kEntranceCaveInteriorCount;
  if (n != ncave + ndun) return;  // pool mismatch — bail (no partial overrides)

  for (int e = 0; e < n; e++) {
    int y = assign[e];
    bool e_cave = (e < ncave);
    bool y_cave = (y < ncave);
    // Resolve endpoint e's door (region R_e + predicate P_e) and, if e is a
    // dungeon, its entry region G_e.
    // G_e is the dungeon's INTERIOR (lobby) region — the gated door edge's
    // to_region. dungeon_door_edge(G_e) then finds THAT edge, returning its
    // from_region (R_e = the spot/waypoint) and predicate (P_e = the door gate,
    // e.g. MM's medallion). Keying on the interior (not the pre-door waypoint)
    // makes the gate travel with the overworld spot (task 2.8). For single-region
    // dungeons interior == entry, so this is unchanged.
    uint16 R_e = 0xFFFF, G_e = 0xFFFF; uint32 Pe_off = 0; uint16 Pe_len = 0;
    if (e_cave) {
      R_e = Rando_FindRegionByName(kCaveInteriors[e].region_name);
    } else {
      const RandoDungeon *de = &kDungeons[didx[e - ncave]];
      G_e = Rando_FindRegionByName(dungeon_override_key(de));
      dungeon_door_edge(G_e, &R_e, &Pe_off, &Pe_len);
    }
    if (y_cave) {
      // Target is a cave: override its locations to e's door region. If e is a
      // gated dungeon door, the cave inherits e's predicate (P_e).
      const RandoCaveInterior *yc = &kCaveInteriors[y];
      for (int k = 0; k < yc->location_count; k++) {
        if (e_cave) {
          Rando_SetEntranceRegionOverride(yc->location_ids[k], R_e);
        } else {
          Rando_SetEntranceRegionOverridePred(yc->location_ids[k], R_e, Pe_off, Pe_len);
        }
      }
      // If e is a dungeon, its original door-edge must be REMOVED (a cave is
      // behind it now) — redirect e's edge to the void sink.
      if (!e_cave && G_e != 0xFFFF) Rando_SetEntranceEdgeOverride(G_e, kCrossVoidRegion);
    } else {
      // Target is a dungeon — land at its INTERIOR (lobby) region G_y.
      const RandoDungeon *dy = &kDungeons[didx[y - ncave]];
      uint16 G_y = Rando_FindRegionByName(dungeon_override_key(dy));
      if (G_y == 0xFFFF) continue;
      if (e_cave) {
        // Dungeon behind a cave door: ADD an unconditional edge cave-region → G_y.
        Rando_AddEntranceEdge(R_e, G_y, 0, 0);
      } else {
        // Dungeon behind a dungeon door: remap e's edge to G_y (keeps P_e).
        if (G_e != 0xFFFF) Rando_SetEntranceEdgeOverride(G_e, G_y);
      }
    }
  }
}

// Build the unified cross door overlay: each door slot → its target endpoint's
// representative entrance-id (cave or dungeon).
void Entrance_BuildCrossOverlay(const uint8 *assign, int n, const uint8 *vanilla,
                                uint32 len, uint8 *overlay) {
  if (vanilla == NULL || overlay == NULL) return;
  memcpy(overlay, vanilla, len);
  if (assign == NULL) return;
  uint8 didx[kEntranceDungeonCount];
  int ndun = cross_dungeon_list(didx);
  const int ncave = kEntranceCaveInteriorCount;
  if (n != ncave + ndun) return;
  for (uint32 d = 0; d < len; d++) {
    // Determine the door's source endpoint from its vanilla entrance-id.
    int e = -1;
    int ci = interior_of_entrance(vanilla[d]);
    if (ci >= 0) {
      e = ci;  // cave endpoint
    } else {
      int dd = dungeon_of_entrance(vanilla[d], kEntranceDungeonCount);
      if (dd >= 0) {
        for (int q = 0; q < ndun; q++) if (didx[q] == dd) { e = ncave + q; break; }
      }
    }
    if (e < 0) continue;  // not a shuffled door (or a TR/GT door — left vanilla)
    int y = assign[e];
    if (y < 0 || y >= n) continue;
    if (y < ncave) overlay[d] = kCaveInteriors[y].entrance_ids[0];
    else overlay[d] = kDungeons[didx[y - ncave]].entrance_id;
  }
}

// True iff door-slot's vanilla entrance-id is a CAVE interior (cached-exit
// class). Used by the runtime to force the cached exit for a cave-source door
// that now loads a dungeon (cross-category). 0 = not a cave door.
bool Entrance_IsCaveEntranceId(uint8 vanilla_entrance_id) {
  return interior_of_entrance(vanilla_entrance_id) >= 0;
}

// Public: cave interior index that entrance-id `ent_id` belongs to, or -1.
// Used by the decoupled runtime (D.4) to key the arrival table by interior.
int Entrance_InteriorOfEntranceId(uint8 ent_id) {
  return interior_of_entrance(ent_id);
}

// Public: the representative (first) entrance-id of cave interior `interior`,
// or 0 if out of range. The decoupled exit replays this door's arrival, and
// uses its kEntranceData_rooms/doorSettings for the Y-adjust (spike iter4).
uint8 Entrance_CaveRepresentativeId(int interior) {
  if (interior < 0 || interior >= kEntranceCaveInteriorCount) return 0;
  return kCaveInteriors[interior].entrance_ids[0];
}

// Public: total cave interior count (the decoupled pool size) + a name for logs.
int Entrance_CaveInteriorCount(void) { return kEntranceCaveInteriorCount; }
const char *Entrance_CaveInteriorName(int interior) {
  if (interior < 0 || interior >= kEntranceCaveInteriorCount) return "(oob)";
  return kCaveInteriors[interior].name;
}

// ---------------------------------------------------------------------------
// Decoupled / per-endpoint ("Insanity", Stage 4 — D.1/D.2: logic + generation)
// ---------------------------------------------------------------------------
bool Entrance_IsDecoupledActive(const RandoSettings *settings) {
  if (settings == NULL || !settings->decoupled) return false;
  // Decoupled composes on top of the cave ENTRY shuffle; caves only for now
  // (dungeon decoupled deferred). Open/Standard like the rest.
  if (!settings->shuffle_cave_entrances) return false;
  return settings->world_state == kWorldState_Open ||
         settings->world_state == kWorldState_Standard;
}

int Entrance_ComputeDecoupledExit(const RandoSettings *settings, uint64 seed,
                                  uint8 attempt, uint8 exit_assign[kEntranceMaxInteriors]) {
  if (exit_assign == NULL || !Entrance_IsDecoupledActive(settings)) return 0;
  const int n = kEntranceCaveInteriorCount;
  for (int i = 0; i < n; i++) exit_assign[i] = (uint8)i;
  RandoRng rng;
  // Distinct salt from cave entry (none), dungeon (0xD0D0…) and cross (0xC2055…)
  // so the exit permutation is independent of the entry permutation in (seed,attempt).
  Rng_SeedFromU64(&rng, (seed ^ 0xE5117E5117E5117Eull) ^
                            ((uint64)attempt * 0x9E3779B97F4A7C15ull));
  for (int i = n - 1; i > 0; i--) {
    uint32 j = Rng_NextRange(&rng, (uint32)(i + 1));
    uint8 t = exit_assign[i]; exit_assign[i] = exit_assign[j]; exit_assign[j] = t;
  }
  return n;
}

void Entrance_ApplyDecoupledExitEdges(const uint8 *exit_assign, int n) {
  if (exit_assign == NULL) return;
  if (n > kEntranceCaveInteriorCount) n = kEntranceCaveInteriorCount;
  // Add the one-way warps ON TOP of any entry/dungeon/cross edge set. Only Begin
  // (which would wipe those) if no edge pass ran this attempt.
  if (!Rando_EntranceEdgeOverridesActive()) Rando_BeginEntranceEdgeOverrides();
  for (int i = 0; i < n; i++) {
    int j = exit_assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) continue;
    if (j == i) continue;  // fixed point = coupled-equivalent self-loop (no new reach)
    uint16 from_r = Rando_FindRegionByName(kCaveInteriors[i].region_name);
    uint16 to_r   = Rando_FindRegionByName(kCaveInteriors[j].region_name);
    if (from_r == 0xFFFF || to_r == 0xFFFF || from_r == to_r) continue;
    // Unconditional: a cave has no access gate beyond reaching its hole, and you
    // can always walk back out. pred_len 0 ⇒ walked unconditionally.
    Rando_AddEntranceEdge(from_r, to_r, 0, 0);
  }
}

void Entrance_WriteDecoupledSpoilerJson(void *file, const uint8 *exit_assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || exit_assign == NULL || n <= 0) return;
  fprintf(f, "  \"decoupled_exit\": [\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = exit_assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    fprintf(f, "    {\"hole\": \"%s\", \"exits_to\": \"%s\"}%s\n",
            kCaveInteriors[i].name, kCaveInteriors[j].name,
            (i + 1 < n && i + 1 < kEntranceCaveInteriorCount) ? "," : "");
  }
  fprintf(f, "  ],\n");
}

void Entrance_WriteDecoupledSpoilerText(void *file, const uint8 *exit_assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || exit_assign == NULL || n <= 0) return;
  fprintf(f, "\nDecoupled exits (enter hole -> emerge at):\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = exit_assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    if (j == i) continue;
    fprintf(f, "  %s -> %s\n", kCaveInteriors[i].name, kCaveInteriors[j].name);
  }
}

// ---------------------------------------------------------------------------
// Spoiler emission
// ---------------------------------------------------------------------------
void Entrance_WriteSpoilerJson(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "  \"entrance_mapping\": [\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    fprintf(f,
        "    {\"door\": \"%s\", \"door_room\": %u, \"leads_to\": \"%s\", "
        "\"leads_to_room\": %u}%s\n",
        kCaveInteriors[i].name, kCaveInteriors[i].room,
        kCaveInteriors[j].name, kCaveInteriors[j].room,
        (i + 1 < n && i + 1 < kEntranceCaveInteriorCount) ? "," : "");
  }
  fprintf(f, "  ],\n");
}

void Entrance_WriteSpoilerText(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "Entrance mapping (coupled cave shuffle):\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    if (j == i) continue;  // text form lists only the moved doors
    fprintf(f, "  %s door -> %s interior (room 0x%03X)\n",
            kCaveInteriors[i].name, kCaveInteriors[j].name, kCaveInteriors[j].room);
  }
}

void Entrance_WriteDungeonSpoilerText(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "Dungeon entrance mapping (coupled):\n");
  for (int i = 0; i < n && i < kEntranceDungeonCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceDungeonCount) j = i;
    fprintf(f, "  %s door -> %s%s\n", kDungeons[i].name, kDungeons[j].name,
            (j == i) ? " (unchanged)" : "");
  }
}

void Entrance_WriteDungeonSpoilerJson(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "  \"dungeon_entrance_mapping\": [\n");
  for (int i = 0; i < n && i < kEntranceDungeonCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceDungeonCount) j = i;
    fprintf(f,
        "    {\"door\": \"%s\", \"leads_to\": \"%s\", \"leads_to_room\": %u}%s\n",
        kDungeons[i].name, kDungeons[j].name, kDungeons[j].room,
        (i + 1 < n && i + 1 < kEntranceDungeonCount) ? "," : "");
  }
  fprintf(f, "  ],\n");
}

// Cross-category endpoint name (combined index). Caller passes the eligible
// dungeon-index list + its count.
static const char *cross_endpoint_name(int e, const uint8 *didx, int ndun) {
  if (e < kEntranceCaveInteriorCount) return kCaveInteriors[e].name;
  int q = e - kEntranceCaveInteriorCount;
  if (q < ndun) return kDungeons[didx[q]].name;
  return "?";
}

void Entrance_WriteCrossSpoilerJson(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  uint8 didx[kEntranceDungeonCount];
  int ndun = cross_dungeon_list(didx);
  if (n != kEntranceCaveInteriorCount + ndun) return;
  fprintf(f, "  \"cross_entrance_mapping\": [\n");
  for (int e = 0; e < n; e++) {
    int y = assign[e];
    if (y < 0 || y >= n) y = e;
    fprintf(f, "    {\"door\": \"%s\", \"leads_to\": \"%s\"}%s\n",
            cross_endpoint_name(e, didx, ndun), cross_endpoint_name(y, didx, ndun),
            (e + 1 < n) ? "," : "");
  }
  fprintf(f, "  ],\n");
}

void Entrance_WriteCrossSpoilerText(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  uint8 didx[kEntranceDungeonCount];
  int ndun = cross_dungeon_list(didx);
  if (n != kEntranceCaveInteriorCount + ndun) return;
  fprintf(f, "Cross-category entrance mapping (caves + dungeons, coupled):\n");
  for (int e = 0; e < n; e++) {
    int y = assign[e];
    if (y < 0 || y >= n) y = e;
    if (y == e) continue;  // list only the moved doors
    fprintf(f, "  %s door -> %s\n",
            cross_endpoint_name(e, didx, ndun), cross_endpoint_name(y, didx, ndun));
  }
}

// ---------------------------------------------------------------------------
// Self-check (pure; no live assets). Uses only the static table + logic_data.
// ---------------------------------------------------------------------------
static const RandoLocationDef *find_location(uint16 id) {
  for (uint32 i = 0; i < kRandoLocationsCount; i++) {
    if (kRandoLocations[i].id == id) return &kRandoLocations[i];
  }
  return NULL;
}

void Entrance_SelfCheck(void) {
  // (0) The cross engine uses kCrossVoidRegion (63) as an unreachable sink to
  //     remove a dungeon's original door-edge (design.md §9 case 3). That only
  //     works if NO real region owns id 63 — otherwise the void redirect would
  //     silently make a live region the sink. Guard it (audit LOW-2): if a future
  //     logic-graph edit ever assigns region 63, this fails the build's selftest
  //     instead of shipping a quietly-wrong reachability model.
  if (strcmp(Rando_GetRegionName(kCrossVoidRegion), "(unbound)") != 0) {
    fprintf(stderr, "Entrance_SelfCheck: kCrossVoidRegion (%d) collides with real "
                    "region '%s' — pick an unused sink id\n",
            kCrossVoidRegion, Rando_GetRegionName(kCrossVoidRegion));
    exit(2);
  }

  // (1) Every entrance-id is unique across interiors (no id backs two interiors)
  //     and every interior's room is in the cached-exit cave class
  //     [0x100,0x180)\{0x104} (so a shuffled cave can never hit the room-keyed
  //     exit SEARCH — review M4).
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    uint16 room = kCaveInteriors[i].room;
    if (!(room >= 0x100 && room < 0x180 && room != 0x104)) {
      fprintf(stderr, "Entrance_SelfCheck: interior %d room 0x%03X outside cave "
                      "class [0x100,0x180)\\{0x104}\n", i, room);
      exit(2);
    }
    for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
      if (interior_of_entrance(kCaveInteriors[i].entrance_ids[k]) != i) {
        fprintf(stderr, "Entrance_SelfCheck: entrance-id 0x%02X maps to the wrong "
                        "interior\n", kCaveInteriors[i].entrance_ids[k]);
        exit(2);
      }
    }
  }

  // (2) Registry↔logic cross-validation: every cave-location's registry region
  //     must equal its region_id in the generated logic table. This catches
  //     registry/logic drift at build time (the otherwise playtest-only seam).
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    const RandoCaveInterior *it = &kCaveInteriors[i];
    if (it->location_count == 0 || it->region_name == NULL) continue;
    uint16 rid = Rando_FindRegionByName(it->region_name);
    if (rid == 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: interior %d region '%s' not found in "
                      "logic regions\n", i, it->region_name);
      exit(2);
    }
    for (int k = 0; k < it->location_count; k++) {
      const RandoLocationDef *loc = find_location(it->location_ids[k]);
      if (loc == NULL) {
        fprintf(stderr, "Entrance_SelfCheck: cave location %u not in logic table\n",
                it->location_ids[k]);
        exit(2);
      }
      if (loc->region_id != rid) {
        fprintf(stderr, "Entrance_SelfCheck: location %u region mismatch — "
                        "registry '%s'(%u) vs logic region_id %u (interior %d). "
                        "Registry/logic drift; fix entrance_registry.yaml or logic.\n",
                it->location_ids[k], it->region_name, rid, loc->region_id, i);
        exit(2);
      }
    }
  }

  // (3) Permutation is a bijection of [0,N).
  RandoSettings s;
  Settings_SetDefaults(&s);
  s.shuffle_cave_entrances = 1;
  s.world_state = kWorldState_Open;
  uint8 assign[kEntranceMaxInteriors];
  int n = Entrance_ComputePermutation(&s, 0xC0FFEEu, 0, assign);
  if (n != kEntranceCaveInteriorCount) {
    fprintf(stderr, "Entrance_SelfCheck: permutation count %d != %d\n",
            n, kEntranceCaveInteriorCount);
    exit(2);
  }
  {
    uint8 seen[kEntranceMaxInteriors];
    memset(seen, 0, sizeof(seen));
    for (int i = 0; i < n; i++) {
      if (assign[i] >= n || seen[assign[i]]) {
        fprintf(stderr, "Entrance_SelfCheck: permutation is not a bijection\n");
        exit(2);
      }
      seen[assign[i]] = 1;
    }
  }

  // (4) Determinism: same (seed, attempt) ⇒ same permutation; different attempt
  //     ⇒ (almost surely) different.
  {
    uint8 a2[kEntranceMaxInteriors];
    Entrance_ComputePermutation(&s, 0xC0FFEEu, 0, a2);
    if (memcmp(assign, a2, n) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: permutation not deterministic\n");
      exit(2);
    }
  }

  // (5) Inactive settings ⇒ no permutation (default-off invariant).
  {
    RandoSettings off;
    Settings_SetDefaults(&off);  // shuffle_cave_entrances default 0
    uint8 a3[kEntranceMaxInteriors];
    if (Entrance_ComputePermutation(&off, 1, 0, a3) != 0 ||
        Entrance_IsActive(&off)) {
      fprintf(stderr, "Entrance_SelfCheck: inactive settings must not shuffle\n");
      exit(2);
    }
    // Inverted/Retro are out of Stage 1 scope even with the axis on.
    RandoSettings inv = s; inv.world_state = kWorldState_Inverted;
    RandoSettings ret = s; ret.world_state = kWorldState_Retro;
    if (Entrance_IsActive(&inv) || Entrance_IsActive(&ret)) {
      fprintf(stderr, "Entrance_SelfCheck: Inverted/Retro must be out of scope\n");
      exit(2);
    }
  }

  // (6) Region-override closed form, asserted via the getter: a forced 2-swap of
  //     two interiors with locations and DIFFERENT regions exchanges their
  //     location regions. interior 10 aginah_cave (LightWorld_South, loc 175)
  //     <-> interior 8 village_chest_game (DarkWorld_NorthWest, loc 215).
  {
    uint16 lws = Rando_FindRegionByName("LightWorld_South");
    uint16 dwnw = Rando_FindRegionByName("DarkWorld_NorthWest");
    if (lws == 0xFFFF || dwnw == 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: region name resolution failed\n");
      exit(2);
    }
    uint8 sw[kEntranceMaxInteriors];
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) sw[i] = (uint8)i;
    sw[10] = 8; sw[8] = 10;
    Entrance_ApplyRegionOverrides(sw, kEntranceCaveInteriorCount);
    // Aginah's loc (175) now reached via village's door ⇒ DWNW; village's loc
    // (215) via aginah's door ⇒ LWS.
    if (Rando_GetEntranceRegionOverride(175) != dwnw ||
        Rando_GetEntranceRegionOverride(215) != lws) {
      fprintf(stderr, "Entrance_SelfCheck: region-override closed form wrong "
                      "(175→%u want %u, 215→%u want %u)\n",
              Rando_GetEntranceRegionOverride(175), dwnw,
              Rando_GetEntranceRegionOverride(215), lws);
      exit(2);
    }
    // Identity permutation ⇒ every cave-location override equals its own region
    // (a no-op), and Clear deactivates so the getter returns 0xFFFF.
    uint8 id[kEntranceMaxInteriors];
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) id[i] = (uint8)i;
    Entrance_ApplyRegionOverrides(id, kEntranceCaveInteriorCount);
    if (Rando_GetEntranceRegionOverride(175) != lws) {
      fprintf(stderr, "Entrance_SelfCheck: identity override must keep own region\n");
      exit(2);
    }
    Entrance_ClearRegionOverrides();
    if (Rando_GetEntranceRegionOverride(175) != 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: Clear must deactivate overrides\n");
      exit(2);
    }
  }

  // (7) Door overlay: build a synthetic vanilla table holding EVERY entrance-id
  //     of every interior (audit L2 — exercise the non-representative ids of
  //     multi-door interiors, e.g. 0x43/0x44 for the tavern, not just
  //     entrance_ids[0]), plus a non-cave sentinel. Each cave door must rewrite
  //     to the representative id of ITS interior's image; non-cave ids pass
  //     through.
  {
    uint8 van[80];
    int slot_interior[80];  // which interior each synthetic door belongs to
    int ndoors = 0;
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
      for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
        van[ndoors] = kCaveInteriors[i].entrance_ids[k];
        slot_interior[ndoors] = i;
        ndoors++;
      }
    }
    van[ndoors] = 0xFE;  // non-cave sentinel
    slot_interior[ndoors] = -1;
    int total = ndoors + 1;
    uint8 ov[80];
    Entrance_BuildDoorOverlay(assign, n, van, (uint32)total, ov);
    for (int d = 0; d < ndoors; d++) {
      uint8 want = kCaveInteriors[assign[slot_interior[d]]].entrance_ids[0];
      if (ov[d] != want) {
        fprintf(stderr, "Entrance_SelfCheck: door overlay door %d (id 0x%02X, "
                        "interior %d) = 0x%02X, want 0x%02X\n",
                d, van[d], slot_interior[d], ov[d], want);
        exit(2);
      }
    }
    if (ov[ndoors] != 0xFE) {
      fprintf(stderr, "Entrance_SelfCheck: non-cave door id was rewritten\n");
      exit(2);
    }
  }

  // (8) DUNGEON pool (Stage 2). Entrance-ids unique + rooms < 0x100; entry
  //     regions resolve, are distinct, and each is the destination of EXACTLY ONE
  //     door-edge in kRandoEdges (drift guard — if the graph changes so a dungeon
  //     entry region gains/loses its single inbound edge, the edge-override key is
  //     no longer well-defined and this fires).
  {
    for (int i = 0; i < kEntranceDungeonCount; i++) {
      if (kDungeons[i].room >= 0x100) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d room 0x%03X not < 0x100\n",
                i, kDungeons[i].room);
        exit(2);
      }
      for (int j = i + 1; j < kEntranceDungeonCount; j++) {
        if (kDungeons[i].entrance_id == kDungeons[j].entrance_id) {
          fprintf(stderr, "Entrance_SelfCheck: duplicate dungeon entrance-id 0x%02X\n",
                  kDungeons[i].entrance_id);
          exit(2);
        }
      }
      uint16 rid = Rando_FindRegionByName(kDungeons[i].entry_region_name);
      if (rid == 0xFFFF) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d entry region '%s' not found\n",
                i, kDungeons[i].entry_region_name);
        exit(2);
      }
      // Audit LOW-3 — the edge-override array is keyed by region id and bounded by
      // kEntranceEdgeOverrideMax (64); a region id ≥ that would be silently dropped
      // on the logic side (runtime redirected, logic identity → desync). Guard it.
      if (rid >= 64) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d region id %u >= edge-override "
                        "bound (64); Set/GetEntranceEdgeOverride would drop it\n", i, rid);
        exit(2);
      }
      // Distinct entry regions.
      for (int j = i + 1; j < kEntranceDungeonCount; j++) {
        if (Rando_FindRegionByName(kDungeons[j].entry_region_name) == rid) {
          fprintf(stderr, "Entrance_SelfCheck: dungeons %d/%d share entry region\n", i, j);
          exit(2);
        }
      }
      // At least one inbound door-edge targets this entry region. Most dungeons
      // have exactly one; Turtle Rock and Ganon's Tower legitimately have TWO
      // (reachable from two overworld Death-Mountain contexts) — the override
      // remaps ALL edges into the region together, which is correct, so >1 is
      // allowed. 0 inbound would mean the override key is unreachable / wrong.
      int inbound = 0;
      for (uint32 e = 0; e < kRandoEdgesCount; e++) {
        if (kRandoEdges[e].to_region == rid) inbound++;
      }
      if (inbound < 1) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d ('%s') entry region has no "
                        "inbound door-edge — edge-override key is unreachable\n",
                i, kDungeons[i].entry_region_name);
        exit(2);
      }
      // The edge-override KEY is the INTERIOR (lobby) region (task 2.8). Validate
      // it the same way: resolves, id < 64 (edge-override array bound), and is the
      // to_region of the dungeon's GATED door edge (so the gate moves with the
      // spot). For single-region dungeons interior == entry, already checked above.
      const char *ikey = dungeon_override_key(&kDungeons[i]);
      uint16 iid = Rando_FindRegionByName(ikey);
      if (iid == 0xFFFF) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d interior region '%s' not found\n",
                i, ikey);
        exit(2);
      }
      if (iid >= 64) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d interior region id %u >= "
                        "edge-override bound (64)\n", i, iid);
        exit(2);
      }
      uint16 dd_from = 0xFFFF; uint32 dd_off = 0; uint16 dd_len = 0;
      if (!dungeon_door_edge(iid, &dd_from, &dd_off, &dd_len)) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon %d interior region '%s' is not the "
                        "to_region of any door-edge — gate would not move with the spot\n",
                i, ikey);
        exit(2);
      }
    }
    // Pool count: base (10) without the GT opt-in, full (11) with it.
    RandoSettings ds; Settings_SetDefaults(&ds);
    ds.shuffle_dungeon_entrances = 1; ds.world_state = kWorldState_Open;
    uint8 dbase[kEntranceMaxInteriors];
    if (Entrance_ComputeDungeonPermutation(&ds, 1, 0, dbase) != kEntranceDungeonBaseCount) {
      fprintf(stderr, "Entrance_SelfCheck: base dungeon pool must be %d (GT excluded)\n",
              kEntranceDungeonBaseCount);
      exit(2);
    }
    // Turn on the Ganon's Tower opt-in for the full-pool permutation tests below.
    ds.shuffle_ganons_tower_entrance = 1;
    uint8 da[kEntranceMaxInteriors], db[kEntranceMaxInteriors];
    int dn = Entrance_ComputeDungeonPermutation(&ds, 0xBEEF, 0, da);
    if (dn != kEntranceDungeonCount) {
      fprintf(stderr, "Entrance_SelfCheck: GT-on dungeon permutation count %d (want %d)\n",
              dn, kEntranceDungeonCount);
      exit(2);
    }
    Entrance_ComputeDungeonPermutation(&ds, 0xBEEF, 0, db);
    if (memcmp(da, db, dn) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: dungeon permutation not deterministic\n");
      exit(2);
    }
    uint8 dseen[kEntranceMaxInteriors]; memset(dseen, 0, sizeof(dseen));
    for (int i = 0; i < dn; i++) {
      if (da[i] >= dn || dseen[da[i]]) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon permutation not a bijection\n");
        exit(2);
      }
      dseen[da[i]] = 1;
    }
    // Edge-override closed form: forced swap of dungeon 0 (PoD) <-> 1 (Swamp)
    // remaps each entry region to the other (verified via the getter).
    uint16 pod = Rando_FindRegionByName(kDungeons[0].entry_region_name);
    uint16 swamp = Rando_FindRegionByName(kDungeons[1].entry_region_name);
    uint8 dsw[kEntranceMaxInteriors];
    for (int i = 0; i < kEntranceDungeonCount; i++) dsw[i] = (uint8)i;
    dsw[0] = 1; dsw[1] = 0;
    Entrance_ApplyEdgeOverrides(dsw, kEntranceDungeonCount);
    if (Rando_GetEntranceEdgeOverride(pod) != swamp ||
        Rando_GetEntranceEdgeOverride(swamp) != pod) {
      fprintf(stderr, "Entrance_SelfCheck: dungeon edge-override closed form wrong\n");
      exit(2);
    }
    Entrance_ClearEdgeOverrides();
    if (Rando_GetEntranceEdgeOverride(pod) != pod) {
      fprintf(stderr, "Entrance_SelfCheck: ClearEdge must restore identity\n");
      exit(2);
    }
    // Dungeon door overlay remap + source-exit-room helper.
    uint8 dv[16], dov[16];
    for (int i = 0; i < kEntranceDungeonCount; i++) dv[i] = kDungeons[i].entrance_id;
    dv[kEntranceDungeonCount] = 0xFE;  // non-dungeon sentinel
    int dtot = kEntranceDungeonCount + 1;
    memcpy(dov, dv, dtot);
    Entrance_RemapDungeonDoors(da, dn, dov, (uint32)dtot);
    for (int i = 0; i < kEntranceDungeonCount; i++) {
      if (dov[i] != kDungeons[da[i]].entrance_id) {
        fprintf(stderr, "Entrance_SelfCheck: dungeon door overlay slot %d wrong\n", i);
        exit(2);
      }
    }
    if (dov[kEntranceDungeonCount] != 0xFE) {
      fprintf(stderr, "Entrance_SelfCheck: non-dungeon id was rewritten\n");
      exit(2);
    }
    if (Entrance_DungeonSourceExitRoom(kDungeons[0].entrance_id) != kDungeons[0].room ||
        Entrance_DungeonSourceExitRoom(0xFE) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: dungeon source-exit-room helper wrong\n");
      exit(2);
    }
  }

  // (9) DECOUPLED (Stage 4 D.1): exit permutation is a bijection over cave holes,
  //     deterministic in (seed, attempt), inactive ⇒ empty, and the exit edges add
  //     only valid region→region warps (skipping fixed points / same-region).
  {
    RandoSettings ds = s;  // s already has shuffle_cave_entrances + Open
    ds.decoupled = 1;
    if (!Entrance_IsDecoupledActive(&ds)) {
      fprintf(stderr, "Entrance_SelfCheck: decoupled should be active for cave+Open\n");
      exit(2);
    }
    uint8 ea[kEntranceMaxInteriors], eb[kEntranceMaxInteriors];
    int en = Entrance_ComputeDecoupledExit(&ds, 0xDEC0, 0, ea);
    if (en != kEntranceCaveInteriorCount) {
      fprintf(stderr, "Entrance_SelfCheck: decoupled count %d != %d\n",
              en, kEntranceCaveInteriorCount);
      exit(2);
    }
    Entrance_ComputeDecoupledExit(&ds, 0xDEC0, 0, eb);
    if (memcmp(ea, eb, en) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: decoupled exit not deterministic\n");
      exit(2);
    }
    uint8 eseen[kEntranceMaxInteriors]; memset(eseen, 0, sizeof(eseen));
    for (int i = 0; i < en; i++) {
      if (ea[i] >= en || eseen[ea[i]]) {
        fprintf(stderr, "Entrance_SelfCheck: decoupled exit not a bijection\n");
        exit(2);
      }
      eseen[ea[i]] = 1;
    }
    // Inactive (no cave shuffle) ⇒ no permutation.
    RandoSettings dn = s; dn.decoupled = 1; dn.shuffle_cave_entrances = 0;
    uint8 e0[kEntranceMaxInteriors];
    if (Entrance_IsDecoupledActive(&dn) ||
        Entrance_ComputeDecoupledExit(&dn, 1, 0, e0) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: decoupled must be inactive without cave shuffle\n");
      exit(2);
    }
    // Apply the exit edges over a clean graph; must activate edge overrides and
    // not crash. (We can't easily assert the added-edge count via a getter, but
    // ApplyDecoupledExitEdges Begins overrides when none are active.)
    Entrance_ClearEdgeOverrides();
    Entrance_ApplyDecoupledExitEdges(ea, en);
    Entrance_ClearEdgeOverrides();
  }

  fprintf(stderr, "[Entrance_SelfCheck] OK\n");
}
