// shuffle_entrance.c — Phase C entrance shuffle, Stage 1. See header.
#include "shuffle_entrance.h"

#include "rando_logic.h"   // Rando_FindRegionByName, Rando_*EntranceRegionOverride*, RandoLocationDef
#include "rando_rng.h"     // RandoRng, Rng_SeedFromU64, Rng_NextRange
#include "rando_settings.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>

// kRandoLocations / kRandoLocationsCount are the generated logic location table
// (logic_data.c). Used only by the self-check's registry↔logic cross-validation.
extern const RandoLocationDef kRandoLocations[];
extern const uint32 kRandoLocationsCount;

// ---------------------------------------------------------------------------
// Static cave-interior table — the data home for cave shuffle.
// === GENERATED by assets/scripts/gen_entrance_table.py from
//     assets/rando/entrance_registry.yaml — do not hand-edit the numeric ids;
//     re-run the script and paste the block below. ===
// ---------------------------------------------------------------------------
typedef struct RandoCaveInterior {
  const char *name;            // interior_id (stable; for the spoiler)
  uint16 room;                 // 0x1xx (cached-exit class [0x100,0x180)\{0x104})
  const char *region_name;     // vanilla logic region of the door (resolved at
                               // runtime via Rando_FindRegionByName; NULL = none)
  const uint8 *entrance_ids;   // overworld entrance-ids that load this interior
  uint8 entrance_count;
  const uint16 *location_ids;  // member locations (NULL when none)
  uint8 location_count;
} RandoCaveInterior;

static const uint8 kEnt_ids_0[1] = { 0x3C };
static const uint8 kEnt_ids_1[2] = { 0x3E, 0x3F };
static const uint8 kEnt_ids_2[1] = { 0x40 };
static const uint8 kEnt_ids_3[3] = { 0x42, 0x43, 0x44 };
static const uint8 kEnt_ids_4[1] = { 0x45 };
static const uint8 kEnt_ids_5[2] = { 0x49, 0x4A };
static const uint8 kEnt_ids_6[1] = { 0x4B };
static const uint8 kEnt_ids_7[1] = { 0x4C };
static const uint8 kEnt_ids_8[2] = { 0x47, 0x48 };
static const uint8 kEnt_ids_9[2] = { 0x53, 0x54 };
static const uint8 kEnt_ids_10[1] = { 0x4D };
static const uint8 kEnt_ids_11[1] = { 0x4E };
static const uint8 kEnt_ids_12[2] = { 0x56, 0x84 };
static const uint8 kEnt_ids_13[1] = { 0x6C };
static const uint8 kEnt_ids_14[2] = { 0x4F, 0x50 };
static const uint8 kEnt_ids_15[1] = { 0x41 };
static const uint8 kEnt_ids_16[1] = { 0x5F };
static const uint8 kEnt_ids_17[2] = { 0x3D, 0x55 };
static const uint8 kEnt_ids_18[1] = { 0x5B };
static const uint8 kEnt_ids_19[2] = { 0x6D, 0x6E };
static const uint8 kEnt_ids_20[1] = { 0x57 };
static const uint8 kEnt_ids_21[2] = { 0x58, 0x5A };
static const uint8 kEnt_ids_22[1] = { 0x59 };
static const uint8 kEnt_ids_23[1] = { 0x60 };
static const uint8 kEnt_ids_24[2] = { 0x5C, 0x62 };
static const uint8 kEnt_ids_25[2] = { 0x5D, 0x5E };
static const uint8 kEnt_ids_26[1] = { 0x63 };
static const uint8 kEnt_ids_27[1] = { 0x67 };
static const uint8 kEnt_ids_28[1] = { 0x61 };
static const uint8 kEnt_ids_29[1] = { 0x68 };
static const uint8 kEnt_ids_30[2] = { 0x51, 0x52 };
static const uint8 kEnt_ids_31[2] = { 0x46, 0x6B };
static const uint8 kEnt_ids_32[1] = { 0x64 };
static const uint8 kEnt_ids_33[2] = { 0x65, 0x66 };
static const uint8 kEnt_ids_34[2] = { 0x69, 0x6A };
static const uint8 kEnt_ids_35[2] = { 0x6F, 0x70 };
static const uint8 kEnt_ids_36[2] = { 0x71, 0x72 };
static const uint8 kEnt_ids_37[1] = { 0x83 };

static const uint16 kEnt_locs_2[1] = { 168 };
static const uint16 kEnt_locs_3[1] = { 153 };
static const uint16 kEnt_locs_4[3] = { 142, 143, 144 };
static const uint16 kEnt_locs_6[1] = { 154 };
static const uint16 kEnt_locs_7[1] = { 147 };
static const uint16 kEnt_locs_8[1] = { 215 };
static const uint16 kEnt_locs_9[1] = { 216 };
static const uint16 kEnt_locs_10[1] = { 175 };
static const uint16 kEnt_locs_11[1] = { 173 };
static const uint16 kEnt_locs_12[1] = { 180 };
static const uint16 kEnt_locs_13[5] = { 176, 177, 178, 179, 185 };
static const uint16 kEnt_locs_14[1] = { 197 };
static const uint16 kEnt_locs_15[1] = { 229 };
static const uint16 kEnt_locs_16[2] = { 206, 207 };
static const uint16 kEnt_locs_17[5] = { 222, 223, 224, 225, 227 };
static const uint16 kEnt_locs_18[1] = { 152 };
static const uint16 kEnt_locs_19[1] = { 165 };

#define kEntranceCaveInteriorCount 38
static const RandoCaveInterior kCaveInteriors[kEntranceCaveInteriorCount] = {
  { /* 0*/ "treasure_shell_game", 0x100, "LightWorld_NorthWest", kEnt_ids_0, 1, 0, 0 },
  { /* 1*/ "snitch_house", 0x101, "LightWorld_NorthWest", kEnt_ids_1, 2, 0, 0 },
  { /* 2*/ "sickboy_house", 0x102, "LightWorld_NorthWest", kEnt_ids_2, 1, kEnt_locs_2, 1 },
  { /* 3*/ "kakariko_tavern", 0x103, "LightWorld_NorthWest", kEnt_ids_3, 3, kEnt_locs_3, 1 },
  { /* 4*/ "sahasrahla_hut", 0x105, "LightWorld_NorthEast", kEnt_ids_4, 1, kEnt_locs_4, 3 },
  { /* 5*/ "kakariko_library", 0x107, "LightWorld_South", kEnt_ids_5, 2, 0, 0 },
  { /* 6*/ "chicken_house", 0x108, "LightWorld_NorthWest", kEnt_ids_6, 1, kEnt_locs_6, 1 },
  { /* 7*/ "potion_shop", 0x109, "LightWorld_NorthEast", kEnt_ids_7, 1, kEnt_locs_7, 1 },
  { /* 8*/ "village_chest_game", 0x106, "DarkWorld_NorthWest", kEnt_ids_8, 2, kEnt_locs_8, 1 },
  { /* 9*/ "bomb_shop", 0x11C, "DarkWorld_NorthWest", kEnt_ids_9, 2, kEnt_locs_9, 1 },
  { /*10*/ "aginah_cave", 0x10A, "LightWorld_South", kEnt_ids_10, 1, kEnt_locs_10, 1 },
  { /*11*/ "watergate", 0x10B, "LightWorld_South", kEnt_ids_11, 1, kEnt_locs_11, 1 },
  { /*12*/ "ice_rod_cave", 0x120, "LightWorld_South", kEnt_ids_12, 2, kEnt_locs_12, 1 },
  { /*13*/ "mini_moldorm_cave", 0x123, "LightWorld_South", kEnt_ids_13, 1, kEnt_locs_13, 5 },
  { /*14*/ "mimic_cave", 0x10C, "LightWorld_DeathMountain_East", kEnt_ids_14, 2, kEnt_locs_14, 1 },
  { /*15*/ "byrna_gauntlet", 0x117, "DarkWorld_DeathMountain_West", kEnt_ids_15, 1, kEnt_locs_15, 1 },
  { /*16*/ "mire_shed", 0x10D, "DarkWorld_Mire", kEnt_ids_16, 1, kEnt_locs_16, 2 },
  { /*17*/ "hype_cave", 0x11E, "DarkWorld_South", kEnt_ids_17, 2, kEnt_locs_17, 5 },
  { /*18*/ "hall_of_invisibility_cape", 0x113, "LightWorld_NorthWest", kEnt_ids_18, 1, kEnt_locs_18, 1 },
  { /*19*/ "thief_hideout", 0x124, "LightWorld_NorthWest", kEnt_ids_19, 2, kEnt_locs_19, 1 },
  { /*20*/ "general_store_1", 0x110, "LightWorld_NorthWest", kEnt_ids_20, 1, 0, 0 },
  { /*21*/ "general_store_2", 0x112, "LightWorld_NorthWest", kEnt_ids_21, 2, 0, 0 },
  { /*22*/ "archery_game", 0x111, "DarkWorld_South", kEnt_ids_22, 1, 0, 0 },
  { /*23*/ "general_store_3", 0x10F, "DarkWorld_NorthWest", kEnt_ids_23, 1, 0, 0 },
  { /*24*/ "pond_of_wishing", 0x114, "LightWorld_NorthEast", kEnt_ids_24, 2, 0, 0 },
  { /*25*/ "pond_of_happiness", 0x115, "LightWorld_South", kEnt_ids_25, 2, 0, 0 },
  { /*26*/ "warped_pond_of_wishing", 0x116, "DarkWorld_NorthWest", kEnt_ids_26, 1, 0, 0 },
  { /*27*/ "chest_shell_game", 0x118, "LightWorld_NorthWest", kEnt_ids_27, 1, 0, 0 },
  { /*28*/ "blinds_old_hideout", 0x119, "DarkWorld_NorthWest", kEnt_ids_28, 1, 0, 0 },
  { /*29*/ "storyteller_cave_4", 0x11A, "DarkWorld_NorthEast", kEnt_ids_29, 1, 0, 0 },
  { /*30*/ "refill_cave_1", 0x11B, "LightWorld_NorthEast", kEnt_ids_30, 2, 0, 0 },
  { /*31*/ "kakariko_lame_shop", 0x11F, "LightWorld_NorthWest", kEnt_ids_31, 2, 0, 0 },
  { /*32*/ "chez_smithies", 0x121, "LightWorld_NorthWest", kEnt_ids_32, 1, 0, 0 },
  { /*33*/ "fortune_teller", 0x122, "LightWorld_NorthWest", kEnt_ids_33, 2, 0, 0 },
  { /*34*/ "storyteller_cave_5", 0x10E, "DarkWorld_NorthEast", kEnt_ids_34, 2, 0, 0 },
  { /*35*/ "thief_hideout_3", 0x125, "LightWorld_NorthWest", kEnt_ids_35, 2, 0, 0 },
  { /*36*/ "fairy_cave_5", 0x126, "LightWorld_NorthWest", kEnt_ids_36, 2, 0, 0 },
  { /*37*/ "heart_piece_cave_3", 0x127, "LightWorld_DeathMountain_West", kEnt_ids_37, 1, 0, 0 },
};
// === end generated block ===

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

bool Entrance_IsActive(const RandoSettings *settings) {
  if (settings == NULL) return false;
  if (!settings->shuffle_cave_entrances) return false;
  // Stage 1 supports cave shuffle on Open/Standard only. Inverted carries a
  // static per-location region override the per-seed override would clobber;
  // Retro re-uses several cave host-rooms for TakeAny. Both deferred.
  if (settings->world_state != kWorldState_Open &&
      settings->world_state != kWorldState_Standard) {
    return false;
  }
  return true;
}

// Map a raw entrance-id to its cave-interior index, or -1 if not a cave.
static int interior_of_entrance(uint8 ent_id) {
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
      if (kCaveInteriors[i].entrance_ids[k] == ent_id) return i;
    }
  }
  return -1;
}

int Entrance_ComputePermutation(const RandoSettings *settings, uint64 seed,
                                uint8 attempt,
                                uint8 assign[kEntranceMaxInteriors]) {
  if (assign == NULL || !Entrance_IsActive(settings)) return 0;
  const int n = kEntranceCaveInteriorCount;
  for (int i = 0; i < n; i++) assign[i] = (uint8)i;

  RandoRng rng;
  // Mix the attempt index into the seed (same constant the placer uses to
  // perturb its retry seed) so each retry draws a distinct permutation while
  // attempt 0 is a pure function of the seed (single-seed determinism).
  Rng_SeedFromU64(&rng, seed ^ ((uint64)attempt * 0x9E3779B97F4A7C15ull));
  // Fisher–Yates over the interior indices (coupled = one bijection).
  for (int i = n - 1; i > 0; i--) {
    uint32 j = Rng_NextRange(&rng, (uint32)(i + 1));
    uint8 t = assign[i]; assign[i] = assign[j]; assign[j] = t;
  }
  return n;
}

void Entrance_ApplyRegionOverrides(const uint8 *assign, int n) {
  Rando_BeginEntranceRegionOverrides();
  if (assign == NULL) return;
  // Audit M3 — clamp the loop bound to the static table (this is a public entry
  // point; the `assign[ix]` value is already range-checked below, but the `ix`
  // index into kCaveInteriors[] must be bounded too).
  if (n > kEntranceCaveInteriorCount) n = kEntranceCaveInteriorCount;
  // For each interior ix (door fixed in vanilla region R[ix]), the interior now
  // reached through ix's door is J = assign[ix]; J's locations become reachable
  // via R[ix]. So override every location of interior J with interior ix's
  // region. assign is a bijection ⇒ each interior's locations are set once.
  for (int ix = 0; ix < n; ix++) {
    const RandoCaveInterior *src = &kCaveInteriors[ix];
    if (src->region_name == NULL) continue;
    uint16 region_id = Rando_FindRegionByName(src->region_name);
    if (region_id == 0xFFFF) continue;  // unknown region name — skip (no-op)
    int j = assign[ix];
    if (j < 0 || j >= kEntranceCaveInteriorCount) continue;
    const RandoCaveInterior *dst = &kCaveInteriors[j];
    for (int k = 0; k < dst->location_count; k++) {
      Rando_SetEntranceRegionOverride(dst->location_ids[k], region_id);
    }
  }
}

void Entrance_ClearRegionOverrides(void) {
  Rando_ClearEntranceRegionOverrides();
}

void Entrance_BuildDoorOverlay(const uint8 *assign, int n,
                               const uint8 *vanilla, uint32 len,
                               uint8 *overlay) {
  if (vanilla == NULL || overlay == NULL || assign == NULL) return;
  memcpy(overlay, vanilla, len);
  for (uint32 d = 0; d < len; d++) {
    int i = interior_of_entrance(vanilla[d]);
    if (i < 0) continue;                 // not a cave door — leave unchanged
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) continue;
    // The door for interior i now loads interior j; write j's representative
    // (first) entrance-id. Coupling is handled by the engine's entry caching.
    overlay[d] = kCaveInteriors[j].entrance_ids[0];
  }
  (void)n;
}

// ---------------------------------------------------------------------------
// Spoiler emission
// ---------------------------------------------------------------------------
void Entrance_WriteSpoilerJson(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "  \"entrance_mapping\": [\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    fprintf(f,
        "    {\"door\": \"%s\", \"door_room\": %u, \"leads_to\": \"%s\", "
        "\"leads_to_room\": %u}%s\n",
        kCaveInteriors[i].name, kCaveInteriors[i].room,
        kCaveInteriors[j].name, kCaveInteriors[j].room,
        (i + 1 < n && i + 1 < kEntranceCaveInteriorCount) ? "," : "");
  }
  fprintf(f, "  ],\n");
}

void Entrance_WriteSpoilerText(void *file, const uint8 *assign, int n) {
  FILE *f = (FILE *)file;
  if (f == NULL || assign == NULL || n <= 0) return;
  fprintf(f, "Entrance mapping (coupled cave shuffle):\n");
  for (int i = 0; i < n && i < kEntranceCaveInteriorCount; i++) {
    int j = assign[i];
    if (j < 0 || j >= kEntranceCaveInteriorCount) j = i;
    if (j == i) continue;  // text form lists only the moved doors
    fprintf(f, "  %s door -> %s interior (room 0x%03X)\n",
            kCaveInteriors[i].name, kCaveInteriors[j].name, kCaveInteriors[j].room);
  }
}

// ---------------------------------------------------------------------------
// Self-check (pure; no live assets). Uses only the static table + logic_data.
// ---------------------------------------------------------------------------
static const RandoLocationDef *find_location(uint16 id) {
  for (uint32 i = 0; i < kRandoLocationsCount; i++) {
    if (kRandoLocations[i].id == id) return &kRandoLocations[i];
  }
  return NULL;
}

void Entrance_SelfCheck(void) {
  // (1) Every entrance-id is unique across interiors (no id backs two interiors)
  //     and every interior's room is in the cached-exit cave class
  //     [0x100,0x180)\{0x104} (so a shuffled cave can never hit the room-keyed
  //     exit SEARCH — review M4).
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    uint16 room = kCaveInteriors[i].room;
    if (!(room >= 0x100 && room < 0x180 && room != 0x104)) {
      fprintf(stderr, "Entrance_SelfCheck: interior %d room 0x%03X outside cave "
                      "class [0x100,0x180)\\{0x104}\n", i, room);
      exit(2);
    }
    for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
      if (interior_of_entrance(kCaveInteriors[i].entrance_ids[k]) != i) {
        fprintf(stderr, "Entrance_SelfCheck: entrance-id 0x%02X maps to the wrong "
                        "interior\n", kCaveInteriors[i].entrance_ids[k]);
        exit(2);
      }
    }
  }

  // (2) Registry↔logic cross-validation: every cave-location's registry region
  //     must equal its region_id in the generated logic table. This catches
  //     registry/logic drift at build time (the otherwise playtest-only seam).
  for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
    const RandoCaveInterior *it = &kCaveInteriors[i];
    if (it->location_count == 0 || it->region_name == NULL) continue;
    uint16 rid = Rando_FindRegionByName(it->region_name);
    if (rid == 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: interior %d region '%s' not found in "
                      "logic regions\n", i, it->region_name);
      exit(2);
    }
    for (int k = 0; k < it->location_count; k++) {
      const RandoLocationDef *loc = find_location(it->location_ids[k]);
      if (loc == NULL) {
        fprintf(stderr, "Entrance_SelfCheck: cave location %u not in logic table\n",
                it->location_ids[k]);
        exit(2);
      }
      if (loc->region_id != rid) {
        fprintf(stderr, "Entrance_SelfCheck: location %u region mismatch — "
                        "registry '%s'(%u) vs logic region_id %u (interior %d). "
                        "Registry/logic drift; fix entrance_registry.yaml or logic.\n",
                it->location_ids[k], it->region_name, rid, loc->region_id, i);
        exit(2);
      }
    }
  }

  // (3) Permutation is a bijection of [0,N).
  RandoSettings s;
  Settings_SetDefaults(&s);
  s.shuffle_cave_entrances = 1;
  s.world_state = kWorldState_Open;
  uint8 assign[kEntranceMaxInteriors];
  int n = Entrance_ComputePermutation(&s, 0xC0FFEEu, 0, assign);
  if (n != kEntranceCaveInteriorCount) {
    fprintf(stderr, "Entrance_SelfCheck: permutation count %d != %d\n",
            n, kEntranceCaveInteriorCount);
    exit(2);
  }
  {
    uint8 seen[kEntranceMaxInteriors];
    memset(seen, 0, sizeof(seen));
    for (int i = 0; i < n; i++) {
      if (assign[i] >= n || seen[assign[i]]) {
        fprintf(stderr, "Entrance_SelfCheck: permutation is not a bijection\n");
        exit(2);
      }
      seen[assign[i]] = 1;
    }
  }

  // (4) Determinism: same (seed, attempt) ⇒ same permutation; different attempt
  //     ⇒ (almost surely) different.
  {
    uint8 a2[kEntranceMaxInteriors];
    Entrance_ComputePermutation(&s, 0xC0FFEEu, 0, a2);
    if (memcmp(assign, a2, n) != 0) {
      fprintf(stderr, "Entrance_SelfCheck: permutation not deterministic\n");
      exit(2);
    }
  }

  // (5) Inactive settings ⇒ no permutation (default-off invariant).
  {
    RandoSettings off;
    Settings_SetDefaults(&off);  // shuffle_cave_entrances default 0
    uint8 a3[kEntranceMaxInteriors];
    if (Entrance_ComputePermutation(&off, 1, 0, a3) != 0 ||
        Entrance_IsActive(&off)) {
      fprintf(stderr, "Entrance_SelfCheck: inactive settings must not shuffle\n");
      exit(2);
    }
    // Inverted/Retro are out of Stage 1 scope even with the axis on.
    RandoSettings inv = s; inv.world_state = kWorldState_Inverted;
    RandoSettings ret = s; ret.world_state = kWorldState_Retro;
    if (Entrance_IsActive(&inv) || Entrance_IsActive(&ret)) {
      fprintf(stderr, "Entrance_SelfCheck: Inverted/Retro must be out of scope\n");
      exit(2);
    }
  }

  // (6) Region-override closed form, asserted via the getter: a forced 2-swap of
  //     two interiors with locations and DIFFERENT regions exchanges their
  //     location regions. interior 10 aginah_cave (LightWorld_South, loc 175)
  //     <-> interior 8 village_chest_game (DarkWorld_NorthWest, loc 215).
  {
    uint16 lws = Rando_FindRegionByName("LightWorld_South");
    uint16 dwnw = Rando_FindRegionByName("DarkWorld_NorthWest");
    if (lws == 0xFFFF || dwnw == 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: region name resolution failed\n");
      exit(2);
    }
    uint8 sw[kEntranceMaxInteriors];
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) sw[i] = (uint8)i;
    sw[10] = 8; sw[8] = 10;
    Entrance_ApplyRegionOverrides(sw, kEntranceCaveInteriorCount);
    // Aginah's loc (175) now reached via village's door ⇒ DWNW; village's loc
    // (215) via aginah's door ⇒ LWS.
    if (Rando_GetEntranceRegionOverride(175) != dwnw ||
        Rando_GetEntranceRegionOverride(215) != lws) {
      fprintf(stderr, "Entrance_SelfCheck: region-override closed form wrong "
                      "(175→%u want %u, 215→%u want %u)\n",
              Rando_GetEntranceRegionOverride(175), dwnw,
              Rando_GetEntranceRegionOverride(215), lws);
      exit(2);
    }
    // Identity permutation ⇒ every cave-location override equals its own region
    // (a no-op), and Clear deactivates so the getter returns 0xFFFF.
    uint8 id[kEntranceMaxInteriors];
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) id[i] = (uint8)i;
    Entrance_ApplyRegionOverrides(id, kEntranceCaveInteriorCount);
    if (Rando_GetEntranceRegionOverride(175) != lws) {
      fprintf(stderr, "Entrance_SelfCheck: identity override must keep own region\n");
      exit(2);
    }
    Entrance_ClearRegionOverrides();
    if (Rando_GetEntranceRegionOverride(175) != 0xFFFF) {
      fprintf(stderr, "Entrance_SelfCheck: Clear must deactivate overrides\n");
      exit(2);
    }
  }

  // (7) Door overlay: build a synthetic vanilla table holding EVERY entrance-id
  //     of every interior (audit L2 — exercise the non-representative ids of
  //     multi-door interiors, e.g. 0x43/0x44 for the tavern, not just
  //     entrance_ids[0]), plus a non-cave sentinel. Each cave door must rewrite
  //     to the representative id of ITS interior's image; non-cave ids pass
  //     through.
  {
    uint8 van[80];
    int slot_interior[80];  // which interior each synthetic door belongs to
    int ndoors = 0;
    for (int i = 0; i < kEntranceCaveInteriorCount; i++) {
      for (int k = 0; k < kCaveInteriors[i].entrance_count; k++) {
        van[ndoors] = kCaveInteriors[i].entrance_ids[k];
        slot_interior[ndoors] = i;
        ndoors++;
      }
    }
    van[ndoors] = 0xFE;  // non-cave sentinel
    slot_interior[ndoors] = -1;
    int total = ndoors + 1;
    uint8 ov[80];
    Entrance_BuildDoorOverlay(assign, n, van, (uint32)total, ov);
    for (int d = 0; d < ndoors; d++) {
      uint8 want = kCaveInteriors[assign[slot_interior[d]]].entrance_ids[0];
      if (ov[d] != want) {
        fprintf(stderr, "Entrance_SelfCheck: door overlay door %d (id 0x%02X, "
                        "interior %d) = 0x%02X, want 0x%02X\n",
                d, van[d], slot_interior[d], ov[d], want);
        exit(2);
      }
    }
    if (ov[ndoors] != 0xFE) {
      fprintf(stderr, "Entrance_SelfCheck: non-cave door id was rewritten\n");
      exit(2);
    }
  }

  fprintf(stderr, "[Entrance_SelfCheck] OK\n");
}
