#!/usr/bin/env python3
"""Fail the build if a large inline data blob is committed.

Generated/extracted data belongs in gitignored artifacts, not inlined into
source as hex. Flags any run of adjacent pure-hex string literals (joined by
concatenation glue) reaching HEX_RUN_THRESHOLD chars — above a SHA-256 (64),
below a real data blob. Allow a true positive with an `embedded-data-guard:
allow <reason>` comment on or just above the line.

Usage: python assets/scripts/check_no_embedded_data.py [--root DIR]
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# 64 bytes. Above any single SHA-256 (64 hex) / asset hash; far below a real
# inline data blob.
HEX_RUN_THRESHOLD = 128

ALLOW_MARKER = "embedded-data-guard: allow"
# A `// GENERATED by <script>` header marks deterministic codegen output mirroring
# a tracked generator (e.g. inverted_maps.c) — the data's source of truth is the
# generator + its input, not the committed copy, so such files are auto-exempt.
GENERATED_MARKER = "GENERATED by"

# String literals: "..." or '...' (no escapes expected inside hex blobs).
_LITERAL_RE = re.compile(r"""(['"])((?:(?!\1).)*)\1""")
_HEX_RE = re.compile(r"\A[0-9a-fA-F]+\Z")
# Characters allowed *between* two adjacent hex literals for them to count as
# one concatenated blob (Python implicit/`+` concat, C "" "" concat, etc.).
_GLUE_RE = re.compile(r"\A[\s+(),\\]*\Z")

# --- C integer-array data-blob detection (the string-literal scan above misses
# `0xNN, 0xNN, ...` initializers). This codebase is a ROM reimplementation full of
# LEGIT large hex tables in src/*.c (messaging/dsp/hud/overworld/...), so a generic
# int-array scan is infeasible — it would flag hundreds of upstream files. Scope it
# to the paths where "no committed extracted data" is the discipline: the rando
# subsystem + the rando-owned Inverted TR collision table in tile_detect.c. A
# contiguous run of >= INT_RUN_THRESHOLD `0xNN` literals (joined only by array glue)
# is a raw data table, not hand-written logic. Escape: a GENERATED header (whole
# file) or an `embedded-data-guard: allow` comment anywhere in the file.
INT_RUN_THRESHOLD = 48
_INT_HEX_RE = re.compile(r"0x[0-9A-Fa-f]{1,4}\b")
_INT_GLUE_RE = re.compile(r"\A[\s,{}()=\[\];]*\Z")
_INT_SCAN_FILES = {"src/tile_detect.c"}
_INT_SCAN_DIRS = ("src/rando/",)

# Only scan textual source/data files. Binary/asset blobs are gitignored anyway.
_TEXT_SUFFIXES = {
    ".py", ".c", ".h", ".cpp", ".cc", ".hpp", ".inc",
    ".yaml", ".yml", ".json", ".txt", ".md", ".cfg", ".ini",
}


def _tracked_files(root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root, capture_output=True, text=True, check=True,
    ).stdout
    return [root / p for p in out.split("\0") if p]


def _line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def scan_file(path: Path) -> list[tuple[int, int]]:
    """Return [(line, hex_len)] for each suspected inline data blob."""
    try:
        text = path.read_text(encoding="utf-8", errors="strict")
    except (UnicodeDecodeError, OSError):
        return []  # not UTF-8 text — skip
    lines = text.splitlines()

    hits: list[tuple[int, int]] = []

    def report(run_len: int, run_start_pos: int) -> None:
        # Report a finished run once, at its TRUE first line, honoring an
        # allow marker on that line or up to 3 lines above it.
        if run_len < HEX_RUN_THRESHOLD:
            return
        ln = _line_of(text, run_start_pos)
        window = "\n".join(lines[max(0, ln - 4):ln])
        if ALLOW_MARKER not in window:
            hits.append((ln, run_len))

    run_len = 0
    run_start_pos = 0
    prev_end = -1
    for m in _LITERAL_RE.finditer(text):
        content = m.group(2)
        is_hex = len(content) >= 8 and len(content) % 2 == 0 and bool(_HEX_RE.match(content))
        if is_hex and run_len > 0 and _GLUE_RE.match(text[prev_end:m.start()]):
            run_len += len(content)          # extend current concatenated run
        else:
            report(run_len, run_start_pos)   # previous run ended — report it
            run_len = len(content) if is_hex else 0
            run_start_pos = m.start()
        prev_end = m.end()
    report(run_len, run_start_pos)           # final run at EOF
    return hits


def _int_scan_applies(rel: str) -> bool:
    rel = rel.replace("\\", "/")
    return rel in _INT_SCAN_FILES or any(rel.startswith(d) for d in _INT_SCAN_DIRS)


def scan_int_array_blob(text: str) -> tuple[int, int] | None:
    """Return (line, run_len) of the first >=threshold contiguous 0xNN run, or None.

    File-level exemption: a GENERATED header or an allow marker anywhere in the
    file suppresses the report (raw data tables live in dedicated files, where a
    file-level declaration is the right granularity — the run repeats per struct
    row, so a per-row window would need a marker on every row)."""
    if GENERATED_MARKER in text[:400] or ALLOW_MARKER in text:
        return None
    run_len = 0
    run_start_pos = 0
    prev_end = -1
    for m in _INT_HEX_RE.finditer(text):
        if run_len > 0 and _INT_GLUE_RE.match(text[prev_end:m.start()]):
            run_len += 1
        else:
            if run_len >= INT_RUN_THRESHOLD:
                return (_line_of(text, run_start_pos), run_len)
            run_len = 1
            run_start_pos = m.start()
        prev_end = m.end()
    if run_len >= INT_RUN_THRESHOLD:
        return (_line_of(text, run_start_pos), run_len)
    return None


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve()
    self_path = Path(__file__).resolve()

    str_violations: list[tuple[Path, int, int]] = []   # (file, line, hex_chars)
    int_violations: list[tuple[Path, int, int]] = []   # (file, line, run_len)
    for f in _tracked_files(root):
        if f.suffix.lower() not in _TEXT_SUFFIXES:
            continue
        if f.resolve() == self_path:
            continue  # this file documents the pattern in prose
        for ln, hex_len in scan_file(f):
            str_violations.append((f, ln, hex_len))
        try:
            rel = str(f.relative_to(root))
        except ValueError:
            rel = str(f)
        if _int_scan_applies(rel):
            try:
                text = f.read_text(encoding="utf-8", errors="strict")
            except (UnicodeDecodeError, OSError):
                text = ""
            hit = scan_int_array_blob(text) if text else None
            if hit is not None:
                int_violations.append((f, hit[0], hit[1]))

    if str_violations or int_violations:
        print("check_no_embedded_data: suspected inline data blob(s) committed:")
        for f, ln, hex_len in str_violations:
            try:
                rel = f.relative_to(root)
            except ValueError:
                rel = f
            print(f"  {rel}:{ln}  — {hex_len} hex chars ({hex_len // 2} bytes) "
                  f"of concatenated hex string literals")
        for f, ln, run_len in int_violations:
            try:
                rel = f.relative_to(root)
            except ValueError:
                rel = f
            print(f"  {rel}:{ln}  — {run_len} contiguous 0xNN integer literals "
                  f"(a raw data table in a rando-data-sensitive path)")
        print(
            "\nGenerated/extracted data belongs in a gitignored build artifact, "
            "read at runtime/codegen (see assets/chest_data.py), not inlined into "
            "source. If this data genuinely belongs in source, add an "
            f"'{ALLOW_MARKER} <reason>' comment (and for codegen output, a "
            "'GENERATED by <script>' header).")
        return 1

    print("check_no_embedded_data: clean — no inline data blobs found.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
