#!/usr/bin/env python3
"""check_door_tables.py — door-shuffle table consistency guard.

The door tables (src/rando/door_tables.gen.{c,h} + assets/rando/
door_predicates.gen.json) are COMMITTED, reference-derived artifacts
(generated by gen_door_tables.py from an ALttPDoorRandomizer checkout, which
CI and fresh clones do not have). This guard catches the fails-open class:

  1. a missing/empty table file (build would die later, but die clearly here);
  2. header counts that disagree with the data file or the frozen registry
     (assets/rando/door_registry.yaml) — a re-numbering invalidates every
     door-shuffle save, so door ids are append-only;
  3. a predicates manifest whose count disagrees with kDoorTbl_VmPredCount.

Run from the repo root (CI: rando_ci.yaml).
"""

import json
import os
import re
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))


def fail(msg):
    print(f'check_door_tables: FAIL: {msg}', file=sys.stderr)
    return 1


def main():
    h_path = os.path.join(REPO, 'src', 'rando', 'door_tables.gen.h')
    c_path = os.path.join(REPO, 'src', 'rando', 'door_tables.gen.c')
    preds_path = os.path.join(REPO, 'assets', 'rando', 'door_predicates.gen.json')
    reg_path = os.path.join(REPO, 'assets', 'rando', 'door_registry.yaml')

    for p in (h_path, c_path, preds_path, reg_path):
        if not os.path.isfile(p) or os.path.getsize(p) == 0:
            return fail(f'missing or empty: {p}')

    with open(h_path, encoding='utf-8') as f:
        h = f.read()
    counts = dict(re.findall(r'#define (kDoorTbl_\w+) (\d+)', h))
    counts = {k: int(v) for k, v in counts.items()}
    for key in ('kDoorTbl_DoorCount', 'kDoorTbl_RegionCount', 'kDoorTbl_EdgeCount',
                'kDoorTbl_PairCount', 'kDoorTbl_DungeonCount', 'kDoorTbl_VmPredCount'):
        if counts.get(key, 0) <= 0:
            return fail(f'{key} missing or zero in door_tables.gen.h')
    if counts['kDoorTbl_DungeonCount'] != 13:
        return fail(f"kDoorTbl_DungeonCount = {counts['kDoorTbl_DungeonCount']}, expected 13")

    with open(c_path, encoding='utf-8') as f:
        c = f.read()
    door_rows = c.count('\n', c.find('kDoorTblDoors['), c.find('};', c.find('kDoorTblDoors['))) - 1
    if door_rows != counts['kDoorTbl_DoorCount']:
        return fail(f"kDoorTblDoors rows {door_rows} != kDoorTbl_DoorCount {counts['kDoorTbl_DoorCount']}")

    # registry: door count must match (ids are append-only; gen_door_tables
    # verifies per-name ids — here we catch a stale regen vs registry edit).
    with open(reg_path, encoding='utf-8') as f:
        reg_ids = re.findall(r'- \{ id: (\d+),', f.read())
    if len(reg_ids) != counts['kDoorTbl_DoorCount']:
        return fail(f"registry has {len(reg_ids)} doors, tables have {counts['kDoorTbl_DoorCount']}")

    with open(preds_path, encoding='utf-8') as f:
        preds = json.load(f)
    if len(preds.get('predicates', [])) != counts['kDoorTbl_VmPredCount']:
        return fail(f"predicates manifest {len(preds.get('predicates', []))} != "
                    f"kDoorTbl_VmPredCount {counts['kDoorTbl_VmPredCount']}")

    print(f"check_door_tables: OK ({counts['kDoorTbl_DoorCount']} doors, "
          f"{counts['kDoorTbl_RegionCount']} regions, "
          f"{counts['kDoorTbl_VmPredCount']} vm preds)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
