#!/usr/bin/env python3
"""Emit the C cave-interior table for entrance shuffle from entrance_registry.yaml.

This is a ONE-SHOT authoring helper, NOT a build-time codegen step (the output
is committed as part of src/rando/shuffle_entrance.c and hand-reviewed). Re-run
it and paste the block if entrance_registry.yaml changes:

    python assets/scripts/gen_entrance_table.py

The table is the data home for Stage 1 cave shuffle: each interior carries its
room, vanilla logic region (by NAME, resolved at runtime via
Rando_FindRegionByName so numeric region-id drift can't silently corrupt it),
its overworld entrance-ids, and the location ids resident inside it.
"""
import sys, os, yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REG = os.path.join(HERE, "..", "rando", "entrance_registry.yaml")

def main():
    with open(REG, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    interiors = data["interiors"]
    out = []
    out.append("// === GENERATED by assets/scripts/gen_entrance_table.py from")
    out.append("//     assets/rando/entrance_registry.yaml — do not hand-edit the")
    out.append("//     numeric ids; re-run the script and paste. ===")
    out.append("static const char *const kCaveEntranceIds_strs = 0;  // (placeholder, see arrays)")
    # entrance-id arrays + location-id arrays per interior
    ent_arrays = []
    loc_arrays = []
    rows = []
    for idx, it in enumerate(interiors):
        eids = it["entrance_ids"]
        locs = it.get("locations") or []
        ename = f"kEnt_ids_{idx}"
        lname = f"kEnt_locs_{idx}" if locs else "0"
        ent_arrays.append(
            f"static const uint8 {ename}[{len(eids)}] = {{ "
            + ", ".join(f"0x{e:02X}" for e in eids) + " };")
        if locs:
            loc_arrays.append(
                f"static const uint16 {lname}[{len(locs)}] = {{ "
                + ", ".join(str(l) for l in locs) + " };")
        rooms = it["rooms"]
        room = rooms[0]
        region = it.get("region") or "0"
        region_c = "NULL" if region in (None, "0") else f"\"{region}\""
        rows.append(
            f'  {{ /*{idx:2d}*/ "{it["interior_id"]}", 0x{room:03X}, {region_c}, '
            f'{ename}, {len(eids)}, {lname}, {len(locs)} }},')
    print("\n".join(ent_arrays))
    print()
    print("\n".join(loc_arrays))
    print()
    print(f"#define kEntranceCaveInteriorCount {len(interiors)}")
    print("static const RandoCaveInterior kCaveInteriors[kEntranceCaveInteriorCount] = {")
    print("\n".join(rows))
    print("};")

if __name__ == "__main__":
    main()
