import argparse
import hashlib
import util
import sys
import os

os.chdir(os.path.dirname(__file__))


def emit_soul_rooms():
  """Generate assets/rando/soul_rooms.gen.yaml from the freshly-compiled
  zelda3_assets.dat + the committed door tables (add-enemy-souls).

  Like chest_table.gen.bin, this is a ROM-derived codegen INPUT that the build
  only CONSUMES — so the fresh-repo extract flow must produce it, or
  souls_shuffle=all fails closed at generation (and `make rando-local-checks`
  fails its freshness check). It needs no built binary (unlike the pot/enemy
  registries, which require a `--dump-*` from a compiled zelda3), so it belongs
  here alongside the asset compile. Best-effort: a warning, not a hard failure,
  keeps public/--no-build flows working. (npc_souls.yaml is committed — no gen
  needed.)
  """
  asset_path = "../zelda3_assets.dat"
  if not os.path.exists(asset_path):
    return  # --no-build or a failed compile; nothing to derive from
  import subprocess
  gen = os.path.join("scripts", "gen_soul_room_tables.py")
  try:
    subprocess.check_call([sys.executable, gen])
  except (subprocess.CalledProcessError, OSError) as exc:
    print(f"restool: WARNING could not generate soul_rooms.gen.yaml ({exc}); "
          f"souls_shuffle=all will fail closed until you run "
          f"`python assets/scripts/gen_soul_room_tables.py`.", file=sys.stderr)


def emit_vanilla_assets_hash():
  """Emit src/rando/vanilla_assets_hash.h with the SHA-256 of zelda3_assets.dat.

  Per tasks.md §1.1b: the header is regenerated whenever the asset pipeline
  runs, so the constant stays in lockstep with the bundled assets. CI fails
  if it would change without an accompanying pipeline change.
  """
  asset_path = "../zelda3_assets.dat"
  if not os.path.exists(asset_path):
    # Nothing to hash yet (e.g., --no-build, or compile_resources failed).
    return
  with open(asset_path, "rb") as fp:
    digest = hashlib.sha256(fp.read()).digest()
  header_path = "../src/rando/vanilla_assets_hash.h"

  # Format the 32-byte digest as 4 rows of 8 hex bytes, like the kPalette_ style.
  rows = []
  for i in range(0, 32, 8):
    rows.append("  " + ", ".join("0x%02x" % b for b in digest[i:i + 8]))
  bytes_block = ",\n".join(rows)

  new_content = (
    "// AUTO-GENERATED by assets/restool.py - DO NOT EDIT BY HAND.\n"
    "// SHA-256 of zelda3_assets.dat at the build that produced this file.\n"
    "// Regenerated on every restool.py invocation that builds the asset blob.\n"
    "// Per tasks.md S1.1b.\n"
    "\n"
    "#ifndef ZELDA3_RANDO_VANILLA_ASSETS_HASH_H_\n"
    "#define ZELDA3_RANDO_VANILLA_ASSETS_HASH_H_\n"
    "\n"
    "#include \"../types.h\"\n"
    "\n"
    # Emit the Known flag so --assets-must-be-vanilla compiles and enforces.
    # dump_vanilla_assets_hash.py emits the same flag — keep the two
    # generators' header output in lockstep (the bundled blob is the reference).
    "#define kVanillaAssetsHashKnown 1\n"
    "\n"
    "static const uint8 kVanillaAssetsHash[32] = {\n"
    + bytes_block + "\n"
    "};\n"
    "\n"
    "#endif  // ZELDA3_RANDO_VANILLA_ASSETS_HASH_H_\n"
  )

  # Only write if content differs - avoid spurious make rebuilds.
  try:
    with open(header_path, "r", encoding="utf-8") as fp:
      if fp.read() == new_content:
        return
  except FileNotFoundError:
    pass

  os.makedirs(os.path.dirname(header_path), exist_ok=True)
  with open(header_path, "w", encoding="utf-8") as fp:
    fp.write(new_content)
  print("Wrote %s (sha256 = %s)" % (header_path, digest.hex()))


parser = argparse.ArgumentParser(description='Resource tool used to build zelda3_assets.dat', allow_abbrev=False)
parser.add_argument('-r', '--rom', nargs='?', metavar='ROM')
parser.add_argument('--extract-from-rom', '-e', action='store_true', help='Extract/overwrite things from the ROM')

optional = parser.add_argument_group('Language settings')
optional.add_argument('--extract-dialogue', action='store_true', help = 'Extract dialogue from a translated ROM')
optional.add_argument('--languages', action='store', metavar='L1,L2', help = 'Comma separated list of additional languages to build (de,fr,fr-c,en,es,pl,pt,redux,nl,sv).')

optional = parser.add_argument_group('Debug things')
optional.add_argument('--no-build', action='store_true', help="Don't actually build zelda3_assets.dat")
optional.add_argument('--print-strings', action='store_true', help="Print all dialogue strings")
optional.add_argument('--print-assets-header', action='store_true')

optional = parser.add_argument_group('Image handling')
optional.add_argument('--sprites-from-png', action='store_true', help="When compiling, load sprites from png instead of from ROM")

args = parser.parse_args()

if args.extract_dialogue:
  ROM = util.load_rom(args.rom, True)
  import extract_resources, sprite_sheets
  sprite_sheets.decode_font()
  extract_resources.print_dialogue()
  sys.exit(0)

ROM = util.load_rom(args.rom)

want_compile = True

if args.extract_from_rom:
  import extract_resources
  extract_resources.main()

if args.print_strings:
  import text_compression
  text_compression.print_strings(ROM)
  want_compile = False

if want_compile and not args.no_build:
  import compile_resources
  compile_resources.main(args)
  emit_vanilla_assets_hash()
  emit_soul_rooms()



